code-4-u/beauty-4-u-BE

- build.gradle
- src/main/java/com/beauty4u/backend/BackendApplication.java
- src/main/java/com/beauty4u/backend/common/common.java
- src/main/java/com/beauty4u/backend/common/exception/CustomException.java
- src/main/java/com/beauty4u/backend/common/exception/CustomExceptionHandler.java
- src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
- src/main/java/com/beauty4u/backend/common/success/CustomSuccess.java
- src/main/java/com/beauty4u/backend/common/success/CustomSuccessHandler.java
- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/common/util/CustomUserUtil.java
- src/main/java/com/beauty4u/backend/config/AppConfig.java
- src/main/java/com/beauty4u/backend/config/SwaggerConfig.java
- src/main/java/com/beauty4u/backend/security/config/SecurityConfig.java
- src/main/java/com/beauty4u/backend/security/dto/LoginRequest.java
- src/main/java/com/beauty4u/backend/security/filter/CustomAuthenticationFilter.java
- src/main/java/com/beauty4u/backend/security/filter/JwtFilter.java
- src/main/java/com/beauty4u/backend/security/handler/JwtAccessDeniedHandler.java
- src/main/java/com/beauty4u/backend/security/handler/JwtAuthenticationEntryPoint.java
- src/main/java/com/beauty4u/backend/security/handler/LoginFailureHandler.java
- src/main/java/com/beauty4u/backend/security/handler/LoginSuccessHandler.java
- src/main/java/com/beauty4u/backend/security/util/CustomUserDetailsService.java
- src/main/java/com/beauty4u/backend/security/util/JwtUtil.java
- src/main/resources/application.yml
🌟개요
---
시큐리티 관련 기능을 추가했습니다. 
스웨거 설정을 추가했습니다.
🌐연결된 Issues
---
Closes #5 
📋작업사항
---
시큐리티 관련 기능 추가
---
스웨거 설정 추가
✅체크리스트
---
> feat: 시큐리티 추가

- src/main/java/com/beauty4u/backend/user/command/application/controller/UserCommandController.java
- src/main/java/com/beauty4u/backend/user/command/application/dto/CreateUserRequest.java
- src/main/java/com/beauty4u/backend/user/command/application/service/UserCommandService.java
- src/main/java/com/beauty4u/backend/user/command/domain/aggregate/UserInfo.java
- src/main/java/com/beauty4u/backend/user/command/domain/repository/DeptRepository.java
- src/main/java/com/beauty4u/backend/user/command/domain/repository/JobRepository.java
- src/main/java/com/beauty4u/backend/user/command/domain/repository/UserRepository.java
- src/main/java/com/beauty4u/backend/user/command/domain/repository/UserRoleRepository.java
- src/main/java/com/beauty4u/backend/user/command/domain/service/UserDomainService.java
🌟개요
---
회원 등록 기능을 구현했습니다.
🌐연결된 Issues
---
Closes #8 
📋작업사항
---
회원 등록 기능 구현 
---
✅체크리스트
---
> feat: 회원 등록 기능 구현 #8

- src/main/java/com/beauty4u/backend/common/exception/CustomException.java
- src/main/java/com/beauty4u/backend/common/exception/CustomExceptionHandler.java
- src/main/java/com/beauty4u/backend/common/response/ApiResponse.java
- src/main/java/com/beauty4u/backend/common/response/ResponseUtil.java
- src/main/java/com/beauty4u/backend/common/success/CustomSuccessHandler.java
- src/main/java/com/beauty4u/backend/user/command/application/controller/UserCommandController.java
🌟개요
---
기존에 커스텀 에러 처리와 커스텀 성공 처리를 공통으로 관리하기 위해 공통 응답 유틸을 구현했습니다.
🌐연결된 Issues
---
Closes #11 
📋작업사항
---
- 공통 응답 유틸 구현
---
✅체크리스트
---
> feat: 공통 응답 유틸 구현

- build.gradle
- src/main/java/com/beauty4u/backend/config/MyBatisConfig.java
- src/main/resources/application.yml
🌟개요
---
MyBatis 설정 추가
🌐연결된 Issues
---
Closes #13 
📋작업사항
---
- MyBatis 설정 추가
---
✅체크리스트
---
> feat: MyBatis 설정 추가

- src/main/java/com/beauty4u/backend/common/util/CustomUserUtil.java
- src/main/java/com/beauty4u/backend/config/SwaggerConfig.java
- src/main/java/com/beauty4u/backend/security/config/SecurityConfig.java
- src/main/java/com/beauty4u/backend/security/filter/JwtFilter.java
- src/main/java/com/beauty4u/backend/security/handler/LoginSuccessHandler.java
- src/main/java/com/beauty4u/backend/security/util/JwtUtil.java
- src/main/resources/application.yml
🌟개요
---
리프레시 토큰 구현했습니다. 
🌐연결된 Issues
---
Closes #10 
📋작업사항
---
- 리프레시 토큰 구현
- 스웨거 설정 추가
- 커스텀 UserUtil 메소드 추가
---
✅체크리스트
---
> feat: 리프레시 토큰 구현

- src/main/java/com/beauty4u/backend/goods/query/controller/GoodsQueryController.java
- src/main/java/com/beauty4u/backend/goods/query/dto/BrandQueryDTO.java
- src/main/java/com/beauty4u/backend/goods/query/mapper/GoodsQueryMapper.java
- src/main/java/com/beauty4u/backend/goods/query/service/GoodsQueryService.java
- src/main/resources/mapper/goods/GoodsMapper.xml
🌟개요
---
- 엘라스틱 서치 구현을 위한 상품 조회
📋작업사항
---
- 상품을 조건 별로 조회할 수 있도록 수정
- 브랜드 별 상품 조회 구현
---
- **상품을 조건 별로 조회할 수 있도록 수정 중입니다.**
✅체크리스트
---
> feat: 상품 조건별 조회, 브랜드 별 조회 구현

- build.gradle
- src/main/java/com/beauty4u/backend/BackendApplication.java
- src/main/java/com/beauty4u/backend/security/config/SecurityConfig.java
- src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/ChattingMessage.java
- src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/Folder.java
- src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/LastRead.java
- src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/Scrap.java
- src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/ScrapReply.java
- src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/Teamspace.java
- src/main/java/com/beauty4u/backend/teamspace/command/domain/repository/ChattingMessageRepository.java
- src/main/java/com/beauty4u/backend/teamspace/query/controller/ChattingMessageController.java
- src/main/java/com/beauty4u/backend/teamspace/query/service/ChattingMessageService.java
- src/main/resources/application.yml
🌟개요
---  mongoDB 연동
🌐연결된 Issues
---
Closes #19 
📋작업사항
--- 채팅 메세지 저장을 위해 Spring과 MongoDB를 연동했습니다.
--- 데이터 조회 예시 코드를 작성했습니다.
--- MongoDB Altas를 사용한 클라우드 연동했습니다.(Free 요금제)
> feat: mongoDB 연동 및 조회 예시 코드 작성 SSP-64

- src/main/java/com/beauty4u/backend/goods/query/mapper/GoodsQueryMapper.java
- src/main/java/com/beauty4u/backend/goods/query/service/GoodsQueryService.java
- src/main/resources/mapper/goods/GoodsMapper.xml
🌟개요
---
엘라스틱 서치 구현을 위한 상품 조회
📋작업사항
---
- 조건별 상품 조회 수정 완료
✅체크리스트
---
> fix: 상품 조건별 조회 수정

- build.gradle
- src/main/java/com/beauty4u/backend/config/redis/RedisConfig.java
- src/main/java/com/beauty4u/backend/config/redis/RedisService.java
- src/main/resources/application.yml
🌟개요
---
레디스 연동 및 관련 메서드 구현
🌐연결된 Issues
---
Closes #23 
📋작업사항
---
- 레디스 연동
- 레디스 관련 메서드 RedisService에 구현
---
✅체크리스트
---
> feat: 레디스 연동 및 관련 메서드 구현

- docker-compose.yml
- src/main/java/com/beauty4u/backend/security/config/SecurityConfig.java
- src/main/java/com/beauty4u/backend/security/filter/JwtFilter.java
- src/main/java/com/beauty4u/backend/security/util/JwtUtil.java
🌟개요
---
레디스 활용 Jwt 로직 구현
🌐연결된 Issues
---
Closes #{이슈넘버}
📋작업사항
---
- 레디스를 활용하여 리프레시 저장 및 검증 구현
- 레디스 도커 컴포즈 설정
---
✅체크리스트
---
> feat: 레디스 활용 Jwt 로직 구현

- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/user/query/controller/UserQueryController.java
- src/main/java/com/beauty4u/backend/user/query/dto/UserListResDTO.java
- src/main/java/com/beauty4u/backend/user/query/mapper/UserQueryMapper.java
- src/main/java/com/beauty4u/backend/user/query/service/UserQueryService.java
- src/main/resources/mapper/user/UserMapper.xml
- src/test/java/com/beauty4u/backend/user/query/service/UserQueryServiceTest.java
🌟개요
---
회원 목록 조회 기능을 구현했습니다. 
🌐연결된 Issues
---
Closes #32 
📋작업사항
---
- 회원 목록 조회 기능 구현
- 테스트 구현
---
✅체크리스트
---
> feat: 회원 목록 조회 구현

- src/main/java/com/beauty4u/backend/customer/command/domain/aggregate/Customer.java
- src/main/java/com/beauty4u/backend/customer/query/controller/CustomerQueryController.java
- src/main/java/com/beauty4u/backend/customer/query/dto/CustomerFilterRequest.java
- src/main/java/com/beauty4u/backend/customer/query/dto/CustomerGrade.java
- src/main/java/com/beauty4u/backend/customer/query/dto/CustomerListResDTO.java
- src/main/java/com/beauty4u/backend/customer/query/mapper/CustomerQueryMapper.java
- src/main/java/com/beauty4u/backend/customer/query/service/CustomerQueryService.java
- src/main/java/com/beauty4u/backend/security/config/SecurityConfig.java
- src/main/resources/mapper/customerMapper/CustomerMapper.xml
🌟개요
---
고객 목록 조회 백 기능 구현
🌐연결된 Issues
---
Closes #27 
📋작업사항
---
- 고객 등급 enum 추가
- 고객 entity에 고객 등급 타입을 추가한 enum으로 변경
- 고객 목록 조회시 반환할 dto 추가
- 페이징 처리로 목록 조회 구현
- mybatis 이용
---
- security config에 모든 url 접근 임시 허용
✅체크리스트
---
> feat: 고객 목록 조회 백 기능 구현

- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/customer/query/controller/CustomerQueryController.java
- src/main/java/com/beauty4u/backend/customer/query/mapper/CustomerQueryMapper.java
- src/main/java/com/beauty4u/backend/customer/query/service/CustomerQueryService.java
- src/main/resources/mapper/customerMapper/CustomerMapper.xml
🌟개요
---
고객 상세 조회 백 기능 구현
🌐연결된 Issues
---
Closes #29 
📋작업사항
---
- 고객 상세 조회 백 기능 구현
- mybatis사용
---
✅체크리스트
---
> feat: 고객 상세 조회 백 기능 구현

- src/main/java/com/beauty4u/backend/elasticsearch/ElasticsearchConfig.java
- src/main/java/com/beauty4u/backend/elasticsearch/ElasticsearchIndexInitializer.java
- src/main/java/com/beauty4u/backend/goods/query/controller/GoodsQueryController.java
- src/main/java/com/beauty4u/backend/goods/query/elasticsearch/document/GoodsDocument.java
- src/main/java/com/beauty4u/backend/goods/query/elasticsearch/repository/GoodsSearchRepository.java
- src/main/java/com/beauty4u/backend/goods/query/service/GoodsQueryService.java
- src/main/resources/application.yml
🌟개요
---
- 엘라스틱 서치를 활용한 검색 기능 구현
- 엘라스틱 서치를 활용한 검색 기능 구현
🌐연결된 Issues
---
Close #6
📋작업사항
---
- 엘라스틱 서치 DB와 동기화
- 엘라스틱 서치 인덱싱 클래스 구현
- 엘라스틱 서치를 활용한 검색 기능 구현
---
✅체크리스트
---
> feat: 엘라스틱 서치 구현 완료 #6

- src/main/java/com/beauty4u/backend/security/config/SecurityConfig.java
- src/main/java/com/beauty4u/backend/security/filter/JwtFilter.java
🌟개요
---
- 시큐리티 일부를 수정했습니다.
🌐연결된 Issues
---
Closes #5 
📋작업사항
---
- 시큐리티 일부 수정
---
✅체크리스트
---
> fix: 시큐리티 수정

- build.gradle
- src/main/java/com/beauty4u/backend/common/util/MailUtil.java
- src/main/resources/application.yml
🌟개요
---
이메일 전송 관련 설정을 추가했습니다.
🌐연결된 Issues
---
Closes #43 
📋작업사항
---
- 이메일 전송 관련 설정 추가
- 이메일 전송 관련 메서드 추가(MailUtil)
---
✅체크리스트
---
> chore: 이메일 전송 관련 설정

- src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
- src/main/java/com/beauty4u/backend/user/command/application/controller/UserCommandController.java
- src/main/java/com/beauty4u/backend/user/command/application/dto/LoginUserReqDTO.java
- src/main/java/com/beauty4u/backend/user/query/controller/UserQueryController.java
- src/main/java/com/beauty4u/backend/user/query/dto/FindUserCodeReqDTO.java
- src/main/java/com/beauty4u/backend/user/query/mapper/UserQueryMapper.java
- src/main/java/com/beauty4u/backend/user/query/service/UserQueryService.java
- src/main/resources/mapper/user/UserMapper.xml
🌟개요
---
- 아이디 찾기 구현
🌐연결된 Issues
---
Closes #42 
📋작업사항
---
- 아이디 찾기 기능 구현
---
- dto 이름 변경
- 안 쓰는 import 정리
✅체크리스트
---
> feat: 아이디 찾기 구현

- src/main/java/com/beauty4u/backend/goods/query/controller/ReviewQueryController.java
- src/main/java/com/beauty4u/backend/goods/query/dto/ReviewQueryDTO.java
- src/main/java/com/beauty4u/backend/goods/query/mapper/ReviewQueryMapper.java
- src/main/java/com/beauty4u/backend/goods/query/service/ReviewQueryService.java
- src/main/resources/mapper/goods/ReviewMapper.xml
🌟개요
---
- 고객 리뷰 조회 기능을 구현하였습니다.
🌐연결된 Issues
---
Closes #49 
📋작업사항
---
- 고객 리뷰 전체 조회
- 리뷰 날짜 정렬 기능
- 리뷰 평점 정렬 기능
---
✅체크리스트
---
> feat: 상품 리뷰 조회

- src/main/java/com/beauty4u/backend/user/command/application/controller/UserCommandController.java
- src/main/java/com/beauty4u/backend/user/command/application/service/UserCommandService.java
- src/main/java/com/beauty4u/backend/user/command/domain/repository/UserRepository.java
- src/main/java/com/beauty4u/backend/user/command/domain/service/UserDomainService.java
- src/main/java/com/beauty4u/backend/user/query/controller/UserQueryController.java
- src/main/java/com/beauty4u/backend/user/query/mapper/UserQueryMapper.java
- src/main/java/com/beauty4u/backend/user/query/service/UserQueryService.java
- src/main/resources/mapper/user/UserMapper.xml
🌟개요
---
- 아이디 찾기 메서드의 위치를 수정했습니다. 
🌐연결된 Issues
---
Closes #42 
📋작업사항
---
- 아이디 찾기 메서드 위치 수정
---
✅체크리스트
---
> refactor: 아이디 찾기 메서드 위치 수정 

- src/main/java/com/beauty4u/backend/user/command/application/controller/UserCommandController.java
- src/main/java/com/beauty4u/backend/user/command/application/dto/FindUserCodeReqDTO.java
- src/main/java/com/beauty4u/backend/user/command/application/dto/ResetUserPasswordReqDTO.java
- src/main/java/com/beauty4u/backend/user/command/application/service/UserCommandService.java
- src/main/java/com/beauty4u/backend/user/command/domain/repository/UserRepository.java
- src/main/java/com/beauty4u/backend/user/command/domain/service/UserDomainService.java
- src/main/java/com/beauty4u/backend/user/query/controller/UserQueryController.java
- src/main/java/com/beauty4u/backend/user/query/mapper/UserQueryMapper.java
- src/main/java/com/beauty4u/backend/user/query/service/UserQueryService.java
- src/main/resources/mapper/user/UserMapper.xml
🌟개요
---
- 비밀번호 재발급을 구현했습니다.
🌐연결된 Issues
---
Closes #47 
📋작업사항
---
- 비밀번호 재발급 기능 구현
---
- 아이디 찾기 요청 dto 위치 수정
✅체크리스트
---
> feat: 비밀번호 재발급 구현

- src/main/java/com/beauty4u/backend/user/query/controller/UserQueryController.java
- src/main/java/com/beauty4u/backend/user/query/dto/FindUserDetailResDTO.java
- src/main/java/com/beauty4u/backend/user/query/mapper/UserQueryMapper.java
- src/main/java/com/beauty4u/backend/user/query/service/UserQueryService.java
- src/main/resources/mapper/user/UserMapper.xml
🌟개요
---
- 내 정보 조회 기능을 구현했습니다.
🌐연결된 Issues
---
Closes #52 
📋작업사항
---
- 내 정보 조회 구현
---
✅체크리스트
---
> feat: 내 정보 조회 구현

- src/main/java/com/beauty4u/backend/user/command/application/controller/UserCommandController.java
- src/main/java/com/beauty4u/backend/user/command/application/dto/UpdateUserPasswordReqDTO.java
- src/main/java/com/beauty4u/backend/user/command/application/service/UserCommandService.java
🌟개요
---
- 비밀번호 수정 기능을 구현했습니다.
🌐연결된 Issues
---
Closes #54 
📋작업사항
---
- 비밀번호 수정 기능 구현
---
✅체크리스트
---
> feat: 비밀번호 수정 구현

- src/main/java/com/beauty4u/backend/user/command/application/controller/UserCommandController.java
- src/main/java/com/beauty4u/backend/user/command/application/dto/AdminResetUserPasswordReqDTO.java
- src/main/java/com/beauty4u/backend/user/command/application/dto/UpdateUserPasswordReqDTO.java
- src/main/java/com/beauty4u/backend/user/command/application/service/UserCommandService.java
🌟개요
---
- 비밀번호 초기화 기능을 구현했습니다. 
🌐연결된 Issues
---
Closes #56 
📋작업사항
---
- 비밀번호 초기화 기능 구현
---
✅체크리스트
---
> feat: 비밀번호 초기화 구현

- src/main/java/com/beauty4u/backend/basesystem/command/domain/aggregate/FileInfo.java
- src/main/java/com/beauty4u/backend/common/aggregate/StatusType.java
- src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/inform/command/application/controller/InformCommandController.java
- src/main/java/com/beauty4u/backend/inform/command/application/dto/CreateInformReqDTO.java
- src/main/java/com/beauty4u/backend/inform/command/application/service/InformCommandService.java
- src/main/java/com/beauty4u/backend/inform/command/domain/aggregate/Inform.java
- src/main/java/com/beauty4u/backend/inform/command/domain/repository/InformRepository.java
- src/main/java/com/beauty4u/backend/inform/command/domain/service/InformDomainService.java
- src/main/java/com/beauty4u/backend/user/command/application/controller/UserCommandController.java
🌟개요
---
- 공지사항 등록 기능을 구현했습니다.
🌐연결된 Issues
---
Closes #60 
📋작업사항
---
- 공지사항 등록 기능 구현
---
- inform 도메인 분리
- 상태타입 공통 enum으로 구현
- 에러코드 수정
- 성공코드 수정
✅체크리스트
---
> feat: 공지사항 등록 구현

- src/main/java/com/beauty4u/backend/basesystem/command/domain/aggregate/FileInfo.java
- src/main/java/com/beauty4u/backend/common/aggregate/StatusType.java
- src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/inform/command/application/controller/InformCommandController.java
- src/main/java/com/beauty4u/backend/inform/command/application/dto/CreateInformReqDTO.java
- src/main/java/com/beauty4u/backend/inform/command/application/dto/InformReqDTO.java
- src/main/java/com/beauty4u/backend/inform/command/application/service/InformCommandService.java
- src/main/java/com/beauty4u/backend/inform/command/domain/aggregate/Inform.java
- src/main/java/com/beauty4u/backend/inform/command/domain/repository/InformRepository.java
- src/main/java/com/beauty4u/backend/inform/command/domain/service/InformDomainService.java
- src/main/java/com/beauty4u/backend/user/command/application/controller/UserCommandController.java
🌟개요
---
- 공지사항 수정 기능을 구현했습니다.
🌐연결된 Issues
---
Closes #62 
📋작업사항
---
- 공지사항 수정 기능 구현
---
- 공지사항 등록 dto 삭제 후 중복되는 dto 통합(공지사항 요청 dto)
✅체크리스트
---
> feat: 공지사항 수정 구현

- src/main/java/com/beauty4u/backend/basesystem/command/domain/aggregate/FileInfo.java
- src/main/java/com/beauty4u/backend/common/aggregate/StatusType.java
- src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/inform/command/application/controller/InformCommandController.java
- src/main/java/com/beauty4u/backend/inform/command/application/dto/CreateInformReqDTO.java
- src/main/java/com/beauty4u/backend/inform/command/application/dto/InformReqDTO.java
- src/main/java/com/beauty4u/backend/inform/command/application/service/InformCommandService.java
- src/main/java/com/beauty4u/backend/inform/command/domain/aggregate/Inform.java
- src/main/java/com/beauty4u/backend/inform/command/domain/repository/InformRepository.java
- src/main/java/com/beauty4u/backend/inform/command/domain/service/InformDomainService.java
- src/main/java/com/beauty4u/backend/user/command/application/controller/UserCommandController.java
🌟개요
---
- 공지사항 삭제 기능을 구현했습니다.
🌐연결된 Issues
---
Closes #64 
📋작업사항
---
- 공지사항 삭제(소프트 삭제) 기능 구현
---
✅체크리스트
---
> feat: 공지사항 삭제 구현

- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/inform/query/controller/InformQueryController.java
- src/main/java/com/beauty4u/backend/inform/query/dto/InformListResDTO.java
- src/main/java/com/beauty4u/backend/inform/query/mapper/InformQueryMapper.java
- src/main/java/com/beauty4u/backend/inform/query/service/InformQueryService.java
- src/main/resources/mapper/inform/InformMapper.xml
🌟개요
---
- 공지사항 목록 조회 기능을 구현했습니다.
🌐연결된 Issues
---
Closes #66 
📋작업사항
---
- 공지사항 목록 조회 기능 구현
---
✅체크리스트
---
> feat: 공지사항 목록 조회 구현

- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/inform/query/controller/InformQueryController.java
- src/main/java/com/beauty4u/backend/inform/query/dto/InformDetailResDTO.java
- src/main/java/com/beauty4u/backend/inform/query/dto/InformListResDTO.java
- src/main/java/com/beauty4u/backend/inform/query/mapper/InformQueryMapper.java
- src/main/java/com/beauty4u/backend/inform/query/service/InformQueryService.java
- src/main/resources/mapper/inform/InformMapper.xml
🌟개요
---
- 공지사항 상세 조회 기능을 구현했습니다.
🌐연결된 Issues
---
Closes #70 
📋작업사항
---
- 공지사항 상세 조회 기능 구현
---
✅체크리스트
---
> feat: 공지사항 상세 조회 구현

- src/main/java/com/beauty4u/backend/basesystem/command/domain/aggregate/FileInfo.java
- src/main/java/com/beauty4u/backend/basesystem/command/domain/aggregate/Noti.java
- src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/inquiry/command/application/controller/InquiryCommandController.java
- src/main/java/com/beauty4u/backend/inquiry/command/application/dto/CreateQnaReqDTO.java
- src/main/java/com/beauty4u/backend/inquiry/command/application/service/InquiryCommandService.java
- src/main/java/com/beauty4u/backend/inquiry/command/domain/aggregate/Faq.java
- src/main/java/com/beauty4u/backend/inquiry/command/domain/aggregate/Inquiry.java
- src/main/java/com/beauty4u/backend/inquiry/command/domain/aggregate/InquiryReply.java
- src/main/java/com/beauty4u/backend/inquiry/command/domain/repository/InquiryRepository.java
- src/main/java/com/beauty4u/backend/inquiry/command/domain/service/InquiryDomainService.java
🌟개요
---
- QnA 질문 등록 기능을 구현했습니다.
🌐연결된 Issues
---
Closes #72 
📋작업사항
---
- QnA 질문 등록 기능 구현
---
- inquiry 도메인 분리 
✅체크리스트
---
> feat: QnA 질문 등록 구현

- src/main/java/com/beauty4u/backend/basesystem/command/domain/aggregate/FileInfo.java
- src/main/java/com/beauty4u/backend/basesystem/command/domain/aggregate/Noti.java
- src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/inquiry/command/application/controller/InquiryCommandController.java
- src/main/java/com/beauty4u/backend/inquiry/command/application/dto/CreateQnaReqDTO.java
- src/main/java/com/beauty4u/backend/inquiry/command/application/dto/QnaReqDTO.java
- src/main/java/com/beauty4u/backend/inquiry/command/application/service/InquiryCommandService.java
- src/main/java/com/beauty4u/backend/inquiry/command/domain/aggregate/Faq.java
- src/main/java/com/beauty4u/backend/inquiry/command/domain/aggregate/Inquiry.java
- src/main/java/com/beauty4u/backend/inquiry/command/domain/aggregate/InquiryReply.java
- src/main/java/com/beauty4u/backend/inquiry/command/domain/repository/InquiryRepository.java
- src/main/java/com/beauty4u/backend/inquiry/command/domain/service/InquiryDomainService.java
🌟개요
---
- QnA 질문 삭제 기능을 구현했습니다.
🌐연결된 Issues
---
Closes #76 
📋작업사항
---
- QnA 질문 삭제 구현
---
✅체크리스트
---
> feat: QnA 질문 삭제 구현

- src/main/java/com/beauty4u/backend/basesystem/command/domain/aggregate/FileInfo.java
- src/main/java/com/beauty4u/backend/basesystem/command/domain/aggregate/Noti.java
- src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/inquiry/command/application/controller/InquiryCommandController.java
- src/main/java/com/beauty4u/backend/inquiry/command/application/controller/InquiryReplyCommandController.java
- src/main/java/com/beauty4u/backend/inquiry/command/application/dto/CreateQnaReqDTO.java
- src/main/java/com/beauty4u/backend/inquiry/command/application/dto/QnaReplyReqDTO.java
- src/main/java/com/beauty4u/backend/inquiry/command/application/dto/QnaReqDTO.java
- src/main/java/com/beauty4u/backend/inquiry/command/application/service/InquiryCommandService.java
- src/main/java/com/beauty4u/backend/inquiry/command/application/service/InquiryReplyCommandService.java
- src/main/java/com/beauty4u/backend/inquiry/command/domain/aggregate/Faq.java
- src/main/java/com/beauty4u/backend/inquiry/command/domain/aggregate/Inquiry.java
- src/main/java/com/beauty4u/backend/inquiry/command/domain/aggregate/InquiryReply.java
- src/main/java/com/beauty4u/backend/inquiry/command/domain/repository/InquiryReplyRepository.java
- src/main/java/com/beauty4u/backend/inquiry/command/domain/repository/InquiryRepository.java
- src/main/java/com/beauty4u/backend/inquiry/command/domain/service/InquiryDomainService.java
- src/main/java/com/beauty4u/backend/inquiry/command/domain/service/InquiryReplyDomainService.java
🌟개요
---
- QnA 답변 등록 기능을 구현했습니다.
🌐연결된 Issues
---
Closes #78 
📋작업사항
---
- QnA 답변 등록 구현
---
✅체크리스트
---
> feat: QnA 답변 등록 구현

- src/main/java/com/beauty4u/backend/analysis/command/domain/aggregate/MarketingSetting.java
- src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/elasticsearch/ElasticsearchIndexInitializer.java
- src/main/java/com/beauty4u/backend/promotion/command/domain/aggregate/PromotionSetting.java
- src/main/java/com/beauty4u/backend/template/command/application/controller/TemplateCommandController.java
- src/main/java/com/beauty4u/backend/template/command/application/dto/CreateTemplateReqDTO.java
- src/main/java/com/beauty4u/backend/template/command/application/dto/UpdateTemplateReqDTO.java
- src/main/java/com/beauty4u/backend/template/command/application/service/TemplateCommandService.java
- src/main/java/com/beauty4u/backend/template/command/domain/aggregate/Template.java
- src/main/java/com/beauty4u/backend/template/command/domain/repository/TemplateRepository.java
- src/main/java/com/beauty4u/backend/template/command/domain/service/TemplateDomainService.java
- src/main/java/com/beauty4u/backend/template/query/controller/TemplateQueryController.java
- src/main/java/com/beauty4u/backend/template/query/dto/TemplateQueryDTO.java
- src/main/java/com/beauty4u/backend/template/query/mapper/TemplateQueryMapper.java
- src/main/java/com/beauty4u/backend/template/query/service/TemplateQueryService.java
- src/main/resources/mapper/template/TemplateMapper.xml
🌟개요
---
템플릿 기본 기능을 구현
🌐연결된 Issues
---
Closes #84 
📋작업사항
---
- 템플릿 등록 기능 구현
- 템플릿 수정 기능 구현
- 템플릿 등록 성공 코드 추가
- 템플릿 수정 성공 코드 추가
---
✅체크리스트
---
> feat: 템플릿 기본 기능 구현

- src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/inquiry/command/application/controller/InquiryReplyCommandController.java
- src/main/java/com/beauty4u/backend/inquiry/command/application/service/InquiryReplyCommandService.java
- src/main/java/com/beauty4u/backend/inquiry/command/domain/aggregate/InquiryReply.java
- src/main/java/com/beauty4u/backend/inquiry/command/domain/repository/InquiryReplyRepository.java
- src/main/java/com/beauty4u/backend/inquiry/command/domain/service/InquiryReplyDomainService.java
🌟개요
---
- QnA 답변 수정 기능을 구현했습니다.
🌐연결된 Issues
---
Closes #80 
📋작업사항
---
- QnA 답변 수정 구현
---
- 엔드포인트 수정
✅체크리스트
---
> feat: QnA 답변 수정 구현

- src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/inquiry/command/application/controller/InquiryReplyCommandController.java
- src/main/java/com/beauty4u/backend/inquiry/command/application/service/InquiryReplyCommandService.java
- src/main/java/com/beauty4u/backend/inquiry/command/domain/aggregate/Inquiry.java
- src/main/java/com/beauty4u/backend/inquiry/command/domain/aggregate/InquiryReply.java
- src/main/java/com/beauty4u/backend/inquiry/command/domain/repository/InquiryReplyRepository.java
- src/main/java/com/beauty4u/backend/inquiry/command/domain/service/InquiryReplyDomainService.java
🌟개요
---
- QnA 답변 삭제 기능을 구현했습니다.
🌐연결된 Issues
---
Closes #82 
📋작업사항
---
- QnA 답변 삭제 구현
---
✅체크리스트
---
> feat: QnA 답변 삭제 구현

- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/template/command/application/controller/TemplateCommandController.java
- src/main/java/com/beauty4u/backend/template/command/application/service/TemplateCommandService.java
- src/main/java/com/beauty4u/backend/template/command/domain/aggregate/Template.java
- src/main/java/com/beauty4u/backend/template/command/domain/service/TemplateDomainService.java
🌟개요
---
템플릿 삭제 기능 구현
🌐연결된 Issues
---
Closes #88 
📋작업사항
---
- 템플릿 삭제 기능 구현
- 템플릿 삭제 성공 코드 추가
- 템플릿 setter 불필요 어노테이션 삭제
---
✅체크리스트
---
> feat: 템플릿 삭제 기능 구현

- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/inquiry/query/controller/InquiryQueryController.java
- src/main/java/com/beauty4u/backend/inquiry/query/dto/InquiryListResDTO.java
- src/main/java/com/beauty4u/backend/inquiry/query/mapper/InquiryQueryMapper.java
- src/main/java/com/beauty4u/backend/inquiry/query/service/InquiryQueryService.java
- src/main/resources/mapper/inquiry/InquiryMapper.xml
🌟개요
---
- QnA 목록 조회 기능을 구현했습니다.
🌐연결된 Issues
---
Closes #96 
📋작업사항
---
- QnA 목록 조회 구현
---
- 이슈번호 #92로 잘못 기재함
✅체크리스트
---
> feat: QnA 목록 조회 구현

- src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/inquiry/command/application/controller/FaqCommandController.java
- src/main/java/com/beauty4u/backend/inquiry/command/application/dto/FaqReqDTO.java
- src/main/java/com/beauty4u/backend/inquiry/command/application/service/FaqService.java
- src/main/java/com/beauty4u/backend/inquiry/command/domain/aggregate/Faq.java
- src/main/java/com/beauty4u/backend/inquiry/command/domain/repository/FaqRepository.java
- src/main/java/com/beauty4u/backend/inquiry/command/domain/service/FaqDomainService.java
🌟개요
---
- FAQ 등록 기능을 구현했습니다.
🌐연결된 Issues
---
Closes #86 
📋작업사항
---
-  FAQ 등록 구현
---
✅체크리스트
---
> feat: FAQ 등록 구현

- src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/inquiry/command/application/controller/FaqCommandController.java
- src/main/java/com/beauty4u/backend/inquiry/command/application/service/FaqService.java
- src/main/java/com/beauty4u/backend/inquiry/command/domain/aggregate/Faq.java
- src/main/java/com/beauty4u/backend/inquiry/command/domain/service/FaqDomainService.java
🌟개요
---
- FAQ 수정 기능을 구현했습니다.
🌐연결된 Issues
---
Closes #103 
📋작업사항
---
- FAQ 수정 구현
---
- faq 엔티티 일부 수정
✅체크리스트
---
> feat: FAQ 수정 구현

- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/inquiry/command/application/controller/FaqCommandController.java
- src/main/java/com/beauty4u/backend/inquiry/command/application/service/FaqService.java
- src/main/java/com/beauty4u/backend/inquiry/command/domain/aggregate/Faq.java
- src/main/java/com/beauty4u/backend/inquiry/command/domain/service/FaqDomainService.java
🌟개요
---
- FAQ 삭제 기능을 구현했습니다.
🌐연결된 Issues
---
Closes #105 
📋작업사항
---
- FAQ 삭제 구현
---
✅체크리스트
---
> feat: FAQ 삭제 구현

- src/main/java/com/beauty4u/backend/customer/query/controller/CustomerQueryController.java
- src/main/java/com/beauty4u/backend/customer/query/dto/CustomerListDTO.java
- src/main/java/com/beauty4u/backend/customer/query/dto/CustomerListResDTO.java
- src/main/java/com/beauty4u/backend/customer/query/dto/CustomerOrderInfoListDTO.java
- src/main/java/com/beauty4u/backend/customer/query/dto/CustomerOrderInfoListResDTO.java
- src/main/java/com/beauty4u/backend/customer/query/mapper/CustomerQueryMapper.java
- src/main/java/com/beauty4u/backend/customer/query/service/CustomerQueryService.java
- src/main/resources/mapper/customer/CustomerMapper.xml
🌟개요
---
고객 도메인 조회 페이징 처리를 위한 로직 추가
🌐연결된 Issues
---
Closes #101 
📋작업사항
---
- 페이징 처리를 위한 mapper 메서드 추가
- 응답 DTO도 변경
- 결과 수를 가져오도록 설정
- 자잘한 오류도 수정
---
✅체크리스트
---
> refactor: 고객 도메인 조회 페이징 처리를 위한 로직 추가

- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/inquiry/query/controller/FaqQueryController.java
- src/main/java/com/beauty4u/backend/inquiry/query/dto/FaqListResDTO.java
- src/main/java/com/beauty4u/backend/inquiry/query/mapper/FaqQueryMapper.java
- src/main/java/com/beauty4u/backend/inquiry/query/service/FaqQueryService.java
- src/main/resources/mapper/inquiry/FaqMapper.xml
🌟개요
---
- FAQ 목록 조회 기능을 구현했습니다.
🌐연결된 Issues
---
Closes #115 
📋작업사항
---
- FAQ 목록 조회 구현
---
✅체크리스트
---
> feat: FAQ 목록 조회 구현

- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/inquiry/query/controller/FaqQueryController.java
- src/main/java/com/beauty4u/backend/inquiry/query/dto/FaqDetailResDTO.java
- src/main/java/com/beauty4u/backend/inquiry/query/mapper/FaqQueryMapper.java
- src/main/java/com/beauty4u/backend/inquiry/query/service/FaqQueryService.java
- src/main/resources/mapper/inquiry/FaqMapper.xml
🌟개요
---
- FAQ 상세 조회 기능을 구현했습니다.
🌐연결된 Issues
---
Closes #117 
📋작업사항
---
- FAQ 상세 조회 구현
---
✅체크리스트
---
> feat: FAQ 상세 조회 구현

- src/main/java/com/beauty4u/backend/elasticsearch/BaseSearchDocument.java
- src/main/java/com/beauty4u/backend/elasticsearch/ElasticsearchConfig.java
- src/main/java/com/beauty4u/backend/elasticsearch/ElasticsearchIndexInitializer.java
- src/main/java/com/beauty4u/backend/goods/query/controller/ReviewQueryController.java
- src/main/java/com/beauty4u/backend/goods/query/elasticsearch/document/GoodsDocument.java
- src/main/java/com/beauty4u/backend/goods/query/elasticsearch/document/ReviewDocument.java
- src/main/java/com/beauty4u/backend/goods/query/elasticsearch/repository/ReviewSearchRepository.java
- src/main/java/com/beauty4u/backend/goods/query/service/GoodsQueryService.java
- src/main/java/com/beauty4u/backend/goods/query/service/ReviewQueryService.java
- src/main/resources/application.yml
- src/main/resources/mapper/goods/ReviewMapper.xml
🌟개요
---
엘라스틱 서치 조회 다른 도메인 사용
🌐연결된 Issues
---
Closes #122 
📋작업사항
---
- 엘라스틱 서치 리뷰 조회
---
✅체크리스트
---
> feat: 엘라스틱 서치 리뷰 조회 구현

- src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/noti/command/application/controller/NotiCommandController.java
- src/main/java/com/beauty4u/backend/noti/command/application/service/NotiService.java
- src/main/java/com/beauty4u/backend/noti/command/domain/aggregate/Noti.java
- src/main/java/com/beauty4u/backend/noti/command/domain/aggregate/NotiType.java
- src/main/java/com/beauty4u/backend/noti/command/domain/repository/NotiRepository.java
- src/main/java/com/beauty4u/backend/noti/command/domain/repository/SseRepository.java
- src/main/java/com/beauty4u/backend/noti/command/domain/service/NotiDomainService.java
- src/main/java/com/beauty4u/backend/noti/query/controller/NotiQueryController.java
- src/main/java/com/beauty4u/backend/noti/query/dto/NotiListResDTO.java
- src/main/java/com/beauty4u/backend/noti/query/mapper/NotiQueryMapper.java
- src/main/java/com/beauty4u/backend/noti/query/service/NotiQueryService.java
- src/main/java/com/beauty4u/backend/user/command/domain/repository/UserRepository.java
- src/main/resources/mapper/noti/NotiMapper.xml
- src/test/java/com/beauty4u/backend/user/query/service/UserQueryServiceTest.java
🌟개요
---
- 알림 조회 기능을 구현했습니다.
🌐연결된 Issues
---
Closes #125 
📋작업사항
---
- 알림 조회 구현
---
✅체크리스트
---
> feat: 알림 조회 구현

- src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/noti/command/application/controller/NotiCommandController.java
- src/main/java/com/beauty4u/backend/noti/command/application/service/NotiService.java
- src/main/java/com/beauty4u/backend/noti/command/domain/aggregate/Noti.java
- src/main/java/com/beauty4u/backend/noti/command/domain/aggregate/NotiType.java
- src/main/java/com/beauty4u/backend/noti/command/domain/repository/NotiRepository.java
- src/main/java/com/beauty4u/backend/noti/command/domain/repository/SseRepository.java
- src/main/java/com/beauty4u/backend/noti/command/domain/service/NotiDomainService.java
- src/main/java/com/beauty4u/backend/user/command/domain/repository/UserRepository.java
- src/test/java/com/beauty4u/backend/user/query/service/UserQueryServiceTest.java
🌟개요
---
- 알림 등록 기능을 구현했습니다.
- SSE를 활용하여 실시간 알림을 구현했습니다.
🌐연결된 Issues
---
Closes #119 
📋작업사항
---
- 알림 등록 구현
- SSE 연결 구현
---
✅체크리스트
---
> feat: 알림 등록 구현

- src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/noti/command/application/controller/NotiCommandController.java
- src/main/java/com/beauty4u/backend/noti/command/application/dto/NotiIdReqDTO.java
- src/main/java/com/beauty4u/backend/noti/command/application/service/NotiService.java
- src/main/java/com/beauty4u/backend/noti/command/domain/aggregate/Noti.java
- src/main/java/com/beauty4u/backend/noti/command/domain/aggregate/NotiType.java
- src/main/java/com/beauty4u/backend/noti/command/domain/repository/NotiRepository.java
- src/main/java/com/beauty4u/backend/noti/command/domain/repository/SseRepository.java
- src/main/java/com/beauty4u/backend/noti/command/domain/service/NotiDomainService.java
- src/main/java/com/beauty4u/backend/noti/query/controller/NotiQueryController.java
- src/main/java/com/beauty4u/backend/noti/query/dto/NotiListResDTO.java
- src/main/java/com/beauty4u/backend/noti/query/mapper/NotiQueryMapper.java
- src/main/java/com/beauty4u/backend/noti/query/service/NotiQueryService.java
- src/main/java/com/beauty4u/backend/user/command/domain/repository/UserRepository.java
- src/main/resources/mapper/noti/NotiMapper.xml
- src/test/java/com/beauty4u/backend/user/query/service/UserQueryServiceTest.java
🌟개요
---
- 알림 읽음 기능을 구현했습니다.
🌐연결된 Issues
---
Closes #128 
📋작업사항
---
-  알림 읽음 구현
---
✅체크리스트
---
> feat: 알림 읽음 구현

- src/main/java/com/beauty4u/backend/user/command/application/dto/CreateUserReqDTO.java
- src/main/java/com/beauty4u/backend/user/command/application/service/UserService.java
- src/main/java/com/beauty4u/backend/user/command/domain/service/UserDomainService.java
- src/test/java/com/beauty4u/backend/user/command/application/service/UserServiceTest.java
🌟개요
---
- 회원 등록 리팩토링 및 테스트 구현
🌐연결된 Issues
---
Closes #8 
📋작업사항
---
- 회원 등록 리팩토링
- 테스트 구현
---
✅체크리스트
---
> refactor, test: 회원 등록 리팩토링 및 테스트 구현

- src/main/java/com/beauty4u/backend/inform/query/controller/InformQueryController.java
- src/main/java/com/beauty4u/backend/inform/query/dto/InformFilterDTO.java
- src/main/java/com/beauty4u/backend/inform/query/dto/InformListDTO.java
- src/main/java/com/beauty4u/backend/inform/query/dto/InformListResDTO.java
- src/main/java/com/beauty4u/backend/inform/query/mapper/InformQueryMapper.java
- src/main/java/com/beauty4u/backend/inform/query/service/InformQueryService.java
- src/main/resources/mapper/inform/InformMapper.xml
🌟개요
---
공지사항 조회 필터링, 정렬 조건 추가
🌐연결된 Issues
---
Closes #126 
📋작업사항
---
- 공지사항 조회에서 필터링, 정렬 조건 추가
- 필터링, 정렬 조건이 포함된 요청 dto 추가
- 응답에서 페이징 처리를 위한 총 개수도 포함 시킴
---
✅체크리스트
---
> refactor: 공지사항 조회 필터링, 정렬 조건 추가

- src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
- src/main/java/com/beauty4u/backend/user/command/application/dto/UpdateUserPasswordReqDTO.java
- src/main/java/com/beauty4u/backend/user/command/application/service/UserService.java
- src/main/java/com/beauty4u/backend/user/command/domain/service/UserDomainService.java
🌟개요
---
- 비밀번호 수정 기능에 현재 비밀번호 검증 로직을 추가했습니다.
🌐연결된 Issues
---
Closes #132 
📋작업사항
---
- 비밀번호 수정 리팩토링
---
✅체크리스트
---
> refactor: 비밀번호 수정 리팩토링

- Dockerfile
- docker-compose.yml
- src/main/java/com/beauty4u/backend/elasticsearch/ElasticsearchIndexInitializer.java
- src/main/java/com/beauty4u/backend/goods/query/controller/GoodsQueryController.java
- src/main/java/com/beauty4u/backend/goods/query/controller/ReviewQueryController.java
- src/main/java/com/beauty4u/backend/goods/query/elasticsearch/document/GoodsDocument.java
- src/main/java/com/beauty4u/backend/goods/query/elasticsearch/repository/GoodsSearchRepository.java
- src/main/java/com/beauty4u/backend/goods/query/elasticsearch/repository/ReviewSearchRepository.java
- src/main/java/com/beauty4u/backend/goods/query/service/GoodsQueryService.java
- src/main/java/com/beauty4u/backend/goods/query/service/ReviewQueryService.java
- src/main/resources/application.yml
- src/main/resources/elasticsearch/mappings/mappings.json
- src/main/resources/elasticsearch/settings/settings.json
🌟개요
---
엘라스틱 서치 설정값을 추가하였습니다.
🌐연결된 Issues
---
Closes #136 
📋작업사항
---
- 엘라스틱 서치 한글형 변환 위한 설정 파일 추가
---
✅체크리스트
---
> feat: 엘라스틱서치 설정값 추가

- src/main/java/com/beauty4u/backend/teamspace/command/domain/repository/TeamSpaceRepository.java
🌟개요
🌐연결된 Issues
Closes #110 
📋작업사항
--- 팀스페이스 엔티티 수정했는데 JPA 레포지토리 미수정해서 다시 올립니다. 
✅체크리스트
> fix: 팀스페이스 레포지토리 수정

- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/user/command/application/controller/UserCommandController.java
- src/main/java/com/beauty4u/backend/user/command/application/dto/CreateUserReqDTO.java
- src/main/java/com/beauty4u/backend/user/command/domain/service/UserDomainService.java
- src/main/java/com/beauty4u/backend/user/query/controller/UserQueryController.java
- src/main/java/com/beauty4u/backend/user/query/dto/DeptResDTO.java
- src/main/java/com/beauty4u/backend/user/query/dto/JobResDTO.java
- src/main/java/com/beauty4u/backend/user/query/dto/RoleResDTO.java
- src/main/java/com/beauty4u/backend/user/query/dto/UserListResDTO.java
- src/main/java/com/beauty4u/backend/user/query/mapper/DeptQueryMapper.java
- src/main/java/com/beauty4u/backend/user/query/mapper/JobQueryMapper.java
- src/main/java/com/beauty4u/backend/user/query/mapper/RoleQueryMapper.java
- src/main/java/com/beauty4u/backend/user/query/service/UserQueryService.java
- src/main/resources/mapper/user/DeptMapper.xml
- src/main/resources/mapper/user/JobMapper.xml
- src/main/resources/mapper/user/RoleMapper.xml
- src/main/resources/mapper/user/UserMapper.xml
- src/test/java/com/beauty4u/backend/user/command/application/service/UserServiceTest.java
🌟개요
---
- 회원 등록 기능을 프론트 구현에 따라 리팩토링했습니다.
🌐연결된 Issues
---
Closes #139 
📋작업사항
---
- 회원 등록 기능 리팩토링
---
✅체크리스트
---
> refactor: 회원 등록 기능 리팩토링

- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/user/command/application/controller/UserCommandController.java
- src/main/java/com/beauty4u/backend/user/command/application/dto/UpdateUserReqDTO.java
- src/main/java/com/beauty4u/backend/user/command/application/service/UserService.java
- src/main/java/com/beauty4u/backend/user/command/domain/aggregate/UserInfo.java
- src/main/java/com/beauty4u/backend/user/command/domain/service/UserDomainService.java
- src/main/java/com/beauty4u/backend/user/query/controller/UserQueryController.java
🌟개요
---
- 회원 정보 수정 기능을 구현했습니다.
🌐연결된 Issues
---
Closes #141 
📋작업사항
---
- 회원 정보 수정 구현
---
- 특정 회원 상세 조회 구현
✅체크리스트
---
> feat: 회원 정보 수정 구현

- build.gradle
- docker-compose.yml
- logstash/pipeline/logstash.conf
- src/main/java/com/beauty4u/backend/elasticsearch/ElasticsearchIndexInitializer.java
- src/main/java/com/beauty4u/backend/goods/query/controller/GoodsQueryController.java
- src/main/java/com/beauty4u/backend/goods/query/controller/ReviewQueryController.java
- src/main/java/com/beauty4u/backend/goods/query/dto/ReviewSortDTO.java
- src/main/java/com/beauty4u/backend/goods/query/elasticsearch/repository/GoodsSearchRepository.java
- src/main/java/com/beauty4u/backend/goods/query/elasticsearch/repository/ReviewSearchRepository.java
- src/main/java/com/beauty4u/backend/goods/query/mapper/ReviewQueryMapper.java
- src/main/java/com/beauty4u/backend/goods/query/service/GoodsQueryService.java
- src/main/java/com/beauty4u/backend/goods/query/service/ReviewQueryService.java
- src/main/resources/application.yml
- src/main/resources/logback.xml
- src/main/resources/mapper/goods/ReviewMapper.xml
🌟개요
---
ELK 도커 실행으로 변경
🌐연결된 Issues
---
Closes #144 
📋작업사항
---
- docker-compose.yml 에 logstash, kibana 설정값 추가
- logstash 사용 위한 logback.xml 파일로 로그 커스튬
- elasticsearch 경로 수정으로 true, false 적용
---
- 실행 시 application.yml > elasticsearch.repositories.eanbled > true 변경
- 리뷰 프론트 기간별 조회, 평점 조회 추가 구현
✅체크리스트
---
> feat: 엘라스틱 서치 도커 연결

- src/main/java/com/beauty4u/backend/basesystem/command/domain/aggregate/FileInfo.java
- src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/schedule/command/application/controller/ScheduleCommandController.java
- src/main/java/com/beauty4u/backend/schedule/command/application/dto/CreateScheduleReqDTO.java
- src/main/java/com/beauty4u/backend/schedule/command/application/dto/ScheduleReqDTO.java
- src/main/java/com/beauty4u/backend/schedule/command/application/service/ScheduleService.java
- src/main/java/com/beauty4u/backend/schedule/command/domain/aggregate/ScheduleInfo.java
- src/main/java/com/beauty4u/backend/schedule/command/domain/aggregate/ScheduleType.java
- src/main/java/com/beauty4u/backend/schedule/command/domain/repository/ScheduleRepository.java
- src/main/java/com/beauty4u/backend/schedule/command/domain/service/ScheduleDomainService.java
- src/main/java/com/beauty4u/backend/schedule/query/controller/ScheduleQueryController.java
- src/main/java/com/beauty4u/backend/schedule/query/dto/ScheduleListResDTO.java
- src/main/java/com/beauty4u/backend/schedule/query/mapper/ScheduleQueryMapper.java
- src/main/java/com/beauty4u/backend/schedule/query/service/ScheduleQueryService.java
- src/main/resources/mapper/schedule/ScheduleMapper.xml
🌟개요
---
- 일정 등록, 수정, 삭제 기능을 구현했습니다.
🌐연결된 Issues
---
Closes #146 
📋작업사항
---
- 일정 등록, 수정, 삭제 구현
---
- 일정 목록 조회 구현
✅체크리스트
---
> feat: 일정 등록, 수정, 삭제 구현

- src/main/resources/logback.xml
🌟개요
---
로그백 에러 수정
🌐연결된 Issues
---
Closes #148 
📋작업사항
---
---
✅체크리스트
---
> fix: logback 의존성 적용 되도록 수정

- src/main/java/com/beauty4u/backend/inquiry/query/controller/FaqQueryController.java
- src/main/java/com/beauty4u/backend/inquiry/query/dto/FaqFilterReqDTO.java
- src/main/java/com/beauty4u/backend/inquiry/query/dto/FaqListDTO.java
- src/main/java/com/beauty4u/backend/inquiry/query/dto/FaqListResDTO.java
- src/main/java/com/beauty4u/backend/inquiry/query/mapper/FaqQueryMapper.java
- src/main/java/com/beauty4u/backend/inquiry/query/service/FaqQueryService.java
- src/main/resources/mapper/inquiry/FaqMapper.xml
🌟개요
---
- FAQ 목록 조회 기능을 리팩토링했습니다.
🌐연결된 Issues
---
Closes #150 
📋작업사항
---
- FAQ 목록 조회 리팩토링 
---
✅체크리스트
---
> refactor: FAQ 목록 조회 리팩토링 

- src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/inform/command/application/dto/InformDTO.java
- src/main/java/com/beauty4u/backend/promotion/command/application/controller/PromotionController.java
- src/main/java/com/beauty4u/backend/promotion/command/application/dto/SavePromotionReqDTO.java
- src/main/java/com/beauty4u/backend/promotion/command/application/service/PromotionService.java
- src/main/java/com/beauty4u/backend/promotion/command/domain/aggregate/Promotion.java
- src/main/java/com/beauty4u/backend/promotion/command/domain/repository/PromotionRepository.java
- src/main/java/com/beauty4u/backend/promotion/command/domain/service/PromotionDomainService.java
- src/main/java/com/beauty4u/backend/promotion/query/controller/PromotionQueryController.java
- src/main/java/com/beauty4u/backend/promotion/query/dto/PromotionDetailResDTO.java
- src/main/java/com/beauty4u/backend/promotion/query/mapper/PromotionMapper.java
- src/main/java/com/beauty4u/backend/promotion/query/service/PromotionQueryService.java
- src/main/resources/mapper/promotion/PromotionMapper.xml
🌟개요
---
프로모션 상세 조회 백 기능 구현
🌐연결된 Issues
---
Closes #155 
📋작업사항
---
- 프로모션 상세 조회 백 기능 구현
- 응답 dto 추가
- modelMapper 사용을 위한 dto 수정
---
✅체크리스트
---
> feat: 프로모션 상세 조회 백 기능 구현

- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/promotion/query/controller/PromotionQueryController.java
- src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionListReqDTO.java
- src/main/java/com/beauty4u/backend/promotion/query/dto/PromotionDetailResDTO.java
- src/main/java/com/beauty4u/backend/promotion/query/mapper/PromotionMapper.java
- src/main/java/com/beauty4u/backend/promotion/query/service/PromotionQueryService.java
- src/main/resources/mapper/promotion/PromotionMapper.xml
🌟개요
---
프로모션 목록 조회 백 기능 구현
🌐연결된 Issues
---
Closes #159 
📋작업사항
---
- 프로모션 목록 조회 백 기능 구현
---
✅체크리스트
---
> feat: 프로모션 목록 조회 백 기능 구현

- src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/promotion/command/application/controller/PromotionController.java
- src/main/java/com/beauty4u/backend/promotion/command/application/service/PromotionService.java
- src/main/java/com/beauty4u/backend/promotion/command/domain/service/PromotionDomainService.java
- src/main/java/com/beauty4u/backend/promotion/query/mapper/PromotionQueryMapper.java
- src/main/java/com/beauty4u/backend/promotion/query/service/PromotionQueryService.java
- src/main/resources/mapper/promotion/PromotionMapper.xml
🌟개요
---
프로모션 수정 백 기능 구현
🌐연결된 Issues
---
Closes #161 
📋작업사항
---
- 프로모션 수정 백 기능 구현
- 프로모션 mapper 이름 수정
---
✅체크리스트
---
> feat: 프로모션 수정 백 기능 구현

- src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/promotion/command/application/controller/PromotionController.java
- src/main/java/com/beauty4u/backend/promotion/command/application/service/PromotionService.java
- src/main/java/com/beauty4u/backend/promotion/command/domain/service/PromotionDomainService.java
- src/main/java/com/beauty4u/backend/promotion/query/mapper/PromotionQueryMapper.java
- src/main/java/com/beauty4u/backend/promotion/query/service/PromotionQueryService.java
- src/main/resources/mapper/promotion/PromotionMapper.xml
🌟개요
---
프로모션 삭제 백 기능 구현
🌐연결된 Issues
---
Closes #163
📋작업사항
---
- 프로모션 삭제 백 기능 구현
---
✅체크리스트
---
> feat: 프로모션 삭제 백 기능 구현

- src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/promotion/command/application/controller/PromotionController.java
- src/main/java/com/beauty4u/backend/promotion/command/application/service/PromotionService.java
- src/main/java/com/beauty4u/backend/promotion/command/domain/service/PromotionDomainService.java
- src/main/java/com/beauty4u/backend/promotion/query/mapper/PromotionQueryMapper.java
- src/main/java/com/beauty4u/backend/promotion/query/service/PromotionQueryService.java
- src/main/java/com/beauty4u/backend/teamspace/command/application/controller/FolderCommandController.java
- src/main/java/com/beauty4u/backend/teamspace/command/application/dto/folder/FindFolderDTO.java
- src/main/java/com/beauty4u/backend/teamspace/command/application/dto/folder/saveFolderDTO.java
- src/main/java/com/beauty4u/backend/teamspace/command/application/dto/teamspace/FindTeamspaceDTO.java
- src/main/java/com/beauty4u/backend/teamspace/command/application/service/FolderService.java
- src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/Folder.java
- src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/Teamspace.java
- src/main/java/com/beauty4u/backend/teamspace/command/domain/service/FolderDomainService.java
- src/main/java/com/beauty4u/backend/teamspace/command/domain/service/TeamspaceDomainService.java
- src/main/resources/mapper/promotion/PromotionMapper.xml
🌟개요
---
폴더 생성 백 기능 구현
🌐연결된 Issues
---
Closes #165 
📋작업사항
---
- 폴더 생성 백 기능 구현
- 연관 관계 객체 조회 시 해당 객체 쪽 domainService 이용
- 계층 간의 이동에서는 DTO로 이동하도록 설정
---
✅체크리스트
---
> feat: 폴더 생성 백 기능 구현

- src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/teamspace/command/application/controller/FolderCommandController.java
- src/main/java/com/beauty4u/backend/teamspace/command/application/dto/folder/UpdateFolderDTO.java
- src/main/java/com/beauty4u/backend/teamspace/command/application/service/FolderService.java
- src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/Folder.java
- src/main/java/com/beauty4u/backend/teamspace/command/domain/service/FolderDomainService.java
🌟개요
---
폴더 수정 백 기능 구현
🌐연결된 Issues
---
Closes #168 
📋작업사항
---
- 폴더 수정 백 기능 구현
- 예외 처리도 같이 구현
---
✅체크리스트
---
> feat: 폴더 수정 백 기능 구현

- src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/teamspace/command/application/controller/FolderCommandController.java
- src/main/java/com/beauty4u/backend/teamspace/command/application/dto/folder/UpdateFolderDTO.java
- src/main/java/com/beauty4u/backend/teamspace/command/application/service/FolderService.java
- src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/Folder.java
- src/main/java/com/beauty4u/backend/teamspace/command/domain/service/FolderDomainService.java
- src/main/java/com/beauty4u/backend/teamspace/query/controller/FolderQueryController.java
- src/main/java/com/beauty4u/backend/teamspace/query/dto/folder/FindFolderListFilterDTO.java
- src/main/java/com/beauty4u/backend/teamspace/query/dto/folder/FolderListResDTO.java
- src/main/java/com/beauty4u/backend/teamspace/query/mapper/FolderQueryMapper.java
- src/main/java/com/beauty4u/backend/teamspace/query/service/FolderQueryService.java
- src/main/resources/mapper/teamSpace/folder/FolderMapper.xml
🌟개요
---
폴더 목록 조회 백 기능 구현
🌐연결된 Issues
---
Closes #170 
📋작업사항
---
- 폴더 목록 조회 백 기능 구현
- 예외 처리도 구현
---
✅체크리스트
---
> feat: 폴더 목록 조회 백 기능 구현

- src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/teamspace/command/application/controller/FolderCommandController.java
- src/main/java/com/beauty4u/backend/teamspace/command/application/service/FolderService.java
- src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/Folder.java
- src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/Scrap.java
- src/main/java/com/beauty4u/backend/teamspace/command/domain/service/FolderDomainService.java
🌟개요
---
폴더 삭제 백 기능 구현
🌐연결된 Issues
---
Closes #172 
📋작업사항
---
- 폴더 삭제 백 기능 구현
- 연관 관계인 스크랩도 삭제되도록 cascade 설정 추가
- 하위의 모든 폴더도 삭제되도록 cascade 설정 추가
---
✅체크리스트
---
> feat: 폴더 삭제 백 기능 구현

- src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/teamspace/command/application/controller/FolderCommandController.java
- src/main/java/com/beauty4u/backend/teamspace/command/application/service/FolderService.java
- src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/Folder.java
- src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/Scrap.java
- src/main/java/com/beauty4u/backend/teamspace/command/domain/repository/FolderRepository.java
- src/main/java/com/beauty4u/backend/teamspace/command/domain/service/FolderDomainService.java
🌟개요
---
폴더 생성, 수정에서 여러 조건 추가
🌐연결된 Issues
---
Closes #175 
📋작업사항
---
- 제일 상위 폴더일 경우 해당 팀 스페이스에서 같은 이름이 존재하는지 확인하는 메서드 추가
- 상위 폴더가 존재할 경우 같은 상위 폴더 내에서 같은 이름이 존재하는지 확인하는 메서드 추가
- 상위 폴더가 존재할 경우 상위 폴더가 삭제되었는지 확인하는 로직 추가
- 각 경우에 대한 예외 처리 구현
---
✅체크리스트
---
> refactor: 폴더 생성, 수정에서 여러 조건 추가

- src/main/java/com/beauty4u/backend/basesystem/command/domain/aggregate/FileInfo.java
- src/main/java/com/beauty4u/backend/basesystem/command/domain/repository/FileRepository.java
- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/inform/command/application/controller/InformCommandController.java
- src/main/java/com/beauty4u/backend/inform/query/service/InformQueryService.java
- src/main/java/com/beauty4u/backend/inquiry/command/application/controller/FaqCommandController.java
- src/main/java/com/beauty4u/backend/inquiry/command/application/controller/InquiryCommandController.java
- src/main/java/com/beauty4u/backend/inquiry/command/application/dto/UpdateFaqViewcount.java
- src/main/java/com/beauty4u/backend/inquiry/command/application/dto/UpdateQnaViewcount.java
- src/main/java/com/beauty4u/backend/inquiry/command/application/service/FaqService.java
- src/main/java/com/beauty4u/backend/inquiry/command/application/service/InquiryService.java
- src/main/java/com/beauty4u/backend/inquiry/command/domain/aggregate/Faq.java
- src/main/java/com/beauty4u/backend/inquiry/command/domain/aggregate/Inquiry.java
- src/main/java/com/beauty4u/backend/inquiry/command/domain/service/FaqDomainService.java
- src/main/java/com/beauty4u/backend/inquiry/command/domain/service/InquiryDomainService.java
- src/main/java/com/beauty4u/backend/inquiry/query/controller/FaqQueryController.java
- src/main/java/com/beauty4u/backend/inquiry/query/controller/InquiryQueryController.java
- src/main/java/com/beauty4u/backend/inquiry/query/dto/FaqDetailResDTO.java
- src/main/java/com/beauty4u/backend/inquiry/query/dto/FaqFilterReqDTO.java
- src/main/java/com/beauty4u/backend/inquiry/query/dto/FaqListResDTO.java
- src/main/java/com/beauty4u/backend/inquiry/query/dto/InquiryDetailResDTO.java
- src/main/java/com/beauty4u/backend/inquiry/query/dto/InquiryFilterReqDTO.java
- src/main/java/com/beauty4u/backend/inquiry/query/dto/InquiryListDTO.java
- src/main/java/com/beauty4u/backend/inquiry/query/dto/InquiryListResDTO.java
- src/main/java/com/beauty4u/backend/inquiry/query/mapper/FaqQueryMapper.java
- src/main/java/com/beauty4u/backend/inquiry/query/mapper/InquiryQueryMapper.java
- src/main/java/com/beauty4u/backend/inquiry/query/service/FaqQueryService.java
- src/main/java/com/beauty4u/backend/inquiry/query/service/InquiryQueryService.java
- src/main/resources/mapper/inquiry/FaqMapper.xml
- src/main/resources/mapper/inquiry/InquiryMapper.xml
🌟개요
---
- FAQ, QnA 리팩토링
🌐연결된 Issues
---
Closes #174 
📋작업사항
---
- FAQ, QnA 리팩토링
---
✅체크리스트
---
> refactor: FAQ, QnA 리팩토링

- src/main/java/com/beauty4u/backend/security/util/CustomUserDetails.java
- src/main/java/com/beauty4u/backend/security/util/CustomUserDetailsService.java
- src/main/java/com/beauty4u/backend/security/util/JwtUtil.java
🌟개요
---
- 액세스토큰에 부서, 직급, 회원이름 추가
🌐연결된 Issues
---
Closes #189 
📋작업사항
---
- 액세스토큰에 부서, 직급, 회원이름 추가
---
✅체크리스트
---
> feat: 액세스토큰에 부서, 직급, 회원이름 추가

- src/main/java/com/beauty4u/backend/security/util/CustomUserDetails.java
- src/main/java/com/beauty4u/backend/security/util/CustomUserDetailsService.java
- src/main/java/com/beauty4u/backend/security/util/JwtUtil.java
🌟개요
---
- 액세스토큰에 부서코드 추가
🌐연결된 Issues
---
Closes #191 
📋작업사항
---
- 액세스토큰에 부서코드 추가
---
✅체크리스트
---
> feat: 액세스토큰에 부서코드 추가

- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/promotion/command/application/controller/PromotionTypeController.java
- src/main/java/com/beauty4u/backend/promotion/command/application/dto/SavePromotionTypeDTO.java
- src/main/java/com/beauty4u/backend/promotion/command/application/service/PromotionTypeService.java
- src/main/java/com/beauty4u/backend/promotion/command/domain/aggregate/PromotionType.java
- src/main/java/com/beauty4u/backend/promotion/command/domain/repository/PromotionTypeRepository.java
- src/main/java/com/beauty4u/backend/promotion/command/domain/service/PromotionTypeDomainService.java
- src/main/resources/mapper/promotion/PromotionMapper.xml
🌟개요
---
프로모션 종류 저장 기능 구현
🌐연결된 Issues
---
Closes #182 
📋작업사항
---
- 프로모션 종류 엔티티 구현
- 프로모션 종류 저장 구현
---
✅체크리스트
---
> feat: 프로모션 종류 저장 기능 구현

- src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/promotion/command/application/controller/PromotionTypeController.java
- src/main/java/com/beauty4u/backend/promotion/command/application/dto/SavePromotionTypeDTO.java
- src/main/java/com/beauty4u/backend/promotion/command/application/dto/UpdatePromotionTypeDTO.java
- src/main/java/com/beauty4u/backend/promotion/command/application/service/PromotionTypeService.java
- src/main/java/com/beauty4u/backend/promotion/command/domain/aggregate/PromotionType.java
- src/main/java/com/beauty4u/backend/promotion/command/domain/repository/PromotionTypeRepository.java
- src/main/java/com/beauty4u/backend/promotion/command/domain/service/PromotionTypeDomainService.java
- src/main/resources/mapper/promotion/PromotionMapper.xml
🌟개요
---
프로모션 종류 수정 기능 구현
🌐연결된 Issues
---
Closes #184 
📋작업사항
---
- 프로모션 종류 수정 기능 구현
- 성공코드, 오류코드 추가
---
✅체크리스트
---
> feat: 프로모션 종류 수정 기능 구현

- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/promotion/query/controller/PromotionTypeQueryController.java
- src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionTypeListDTO.java
- src/main/java/com/beauty4u/backend/promotion/query/dto/PromotionTypeFilterDTO.java
- src/main/java/com/beauty4u/backend/promotion/query/mapper/PromotionTypeQueryMapper.java
- src/main/java/com/beauty4u/backend/promotion/query/service/PromotionTypeQueryService.java
- src/main/resources/mapper/promotion/PromotionTypeMapper.xml
🌟개요
---
프로모션 종류 목록 조회 구현
🌐연결된 Issues
---
Closes #185 
📋작업사항
---
- 프로모션 종류 목록 조회
- 페이징 처리 구현
---
✅체크리스트
---
> feat: 프로모션 종류 목록 조회 구현

- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/promotion/command/domain/aggregate/Promotion.java
- src/main/java/com/beauty4u/backend/promotion/query/controller/PromotionTypeQueryController.java
- src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionTypeDetailDTO.java
- src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionTypeListDTO.java
- src/main/java/com/beauty4u/backend/promotion/query/dto/PromotionTypeFilterDTO.java
- src/main/java/com/beauty4u/backend/promotion/query/mapper/PromotionTypeQueryMapper.java
- src/main/java/com/beauty4u/backend/promotion/query/service/PromotionTypeQueryService.java
- src/main/resources/mapper/promotion/PromotionTypeMapper.xml
🌟개요
---
프로모션 종류 상세 조회 백 기능 구현
🌐연결된 Issues
---
Closes #186 
📋작업사항
---
- 프로모션 종류 상세 조회 백 기능 구현
- 프로모션 종류에 대한 프로모션 목록도 같이 조회 가능
---
✅체크리스트
---
> feat: 프로모션 종류 상세 조회 백 기능 구현

- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/promotion/command/application/controller/PromotionTypeController.java
- src/main/java/com/beauty4u/backend/promotion/command/application/service/PromotionTypeService.java
- src/main/java/com/beauty4u/backend/promotion/command/domain/aggregate/Promotion.java
- src/main/java/com/beauty4u/backend/promotion/command/domain/aggregate/PromotionType.java
- src/main/java/com/beauty4u/backend/promotion/command/domain/service/PromotionTypeDomainService.java
- src/main/java/com/beauty4u/backend/promotion/query/controller/PromotionTypeQueryController.java
- src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionTypeDetailDTO.java
- src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionTypeListDTO.java
- src/main/java/com/beauty4u/backend/promotion/query/dto/PromotionTypeFilterDTO.java
- src/main/java/com/beauty4u/backend/promotion/query/mapper/PromotionTypeQueryMapper.java
- src/main/java/com/beauty4u/backend/promotion/query/service/PromotionTypeQueryService.java
- src/main/resources/mapper/promotion/PromotionTypeMapper.xml
🌟개요
---
프로모션 종류 삭제 기능 구현
🌐연결된 Issues
---
Closes #187 
📋작업사항
---
- 프로모션 종류 삭제 기능 구현
- 프로모션 종류와 관련된 엔티티 삭제를 위한 엔티티 설정 추가
---
✅체크리스트
---
> feat: 프로모션 종류 삭제 기능 구현

- src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
- src/main/java/com/beauty4u/backend/promotion/command/application/dto/SavePromotionReqDTO.java
- src/main/java/com/beauty4u/backend/promotion/command/application/service/PromotionService.java
- src/main/java/com/beauty4u/backend/promotion/query/controller/PromotionQueryController.java
- src/main/java/com/beauty4u/backend/promotion/query/dto/PromotionDetailResDTO.java
- src/main/java/com/beauty4u/backend/promotion/query/service/PromotionQueryService.java
- src/main/resources/mapper/promotion/PromotionMapper.xml
- src/main/resources/mapper/promotion/PromotionTypeMapper.xml
🌟개요
---
프로모션 crud 리팩토링
🌐연결된 Issues
---
Closes #198 
📋작업사항
---
- 프로모션 수정, 삭제 시 프로모션 종류도 사용하도록 수정
- 프로모션 기본 리팩토링 진행
---
✅체크리스트
---
> feat: 프로모션 기본 리팩토링

- src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/goods/command/domain/repository/GoodsRepository.java
- src/main/java/com/beauty4u/backend/promotion/command/application/controller/PromotionGoodsController.java
- src/main/java/com/beauty4u/backend/promotion/command/application/controller/PromotionTypeController.java
- src/main/java/com/beauty4u/backend/promotion/command/application/dto/SaveGoodsDiscountDTO.java
- src/main/java/com/beauty4u/backend/promotion/command/application/dto/SavePromotionGoodsDTO.java
- src/main/java/com/beauty4u/backend/promotion/command/application/dto/SavePromotionGoodsReqDTO.java
- src/main/java/com/beauty4u/backend/promotion/command/application/service/PromotionGoodsService.java
- src/main/java/com/beauty4u/backend/promotion/command/domain/aggregate/Promotion.java
- src/main/java/com/beauty4u/backend/promotion/command/domain/repository/PromotionGoodsRepository.java
- src/main/java/com/beauty4u/backend/promotion/command/domain/service/PromotionGoodsDomainService.java
- src/main/java/com/beauty4u/backend/promotion/query/controller/PromotionTypeQueryController.java
- src/main/java/com/beauty4u/backend/promotion/query/dto/PromotionTypeFilterDTO.java
- src/main/resources/mapper/promotion/PromotionTypeMapper.xml
🌟개요
---
프로모션 상품 등록 백 기능 구현
🌐연결된 Issues
---
Closes #201 
📋작업사항
---
- 프로모션 상품 등록 백 기능 구현
- 프로모션 목록 조회 오류 해결
- 프로모션 매핑 관계 오류 해결
---
✅체크리스트
---
> feat: 프로모션 상품 등록 백 기능 구현

- src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/promotion/command/application/controller/PromotionGoodsController.java
- src/main/java/com/beauty4u/backend/promotion/command/application/dto/DeletePromotionGoodsReqDTO.java
- src/main/java/com/beauty4u/backend/promotion/command/application/service/PromotionGoodsService.java
- src/main/java/com/beauty4u/backend/promotion/command/domain/service/PromotionGoodsDomainService.java
🌟개요
---
프로모션 적용 상품 삭제 백 기능 구현
🌐연결된 Issues
---
Closes #203 
📋작업사항
---
- 프로모션 적용 상품 목록으로 삭제 기능 구현
- id 값들만 받아서 목록으로 삭제 구현
---
✅체크리스트
---
> feat: 프로모션 적용 상품 삭제 백 기능 구현

- src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/promotion/command/application/controller/PromotionGoodsController.java
- src/main/java/com/beauty4u/backend/promotion/command/application/dto/DeletePromotionGoodsReqDTO.java
- src/main/java/com/beauty4u/backend/promotion/command/application/dto/UpdatePromotionGoodsReqDTO.java
- src/main/java/com/beauty4u/backend/promotion/command/application/service/PromotionGoodsService.java
- src/main/java/com/beauty4u/backend/promotion/command/domain/service/PromotionGoodsDomainService.java
🌟개요
---
프로모션 상품 할인율 수정 백 기능 구현
🌐연결된 Issues
---
Closes #205 
📋작업사항
---
- 프로모션 상품 할인율 수정 백 기능 구현
- 개별로 하나씩 수정을 해야함
- 목록으로 다같이 수정하는것이 아님
---
✅체크리스트
---
> feat: 프로모션 상품 할인율 수정 백 기능 구현

- src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/promotion/query/controller/PromotionGoodsQueryController.java
- src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionGoodsListFilterDTO.java
- src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionGoodsListResDTO.java
- src/main/java/com/beauty4u/backend/promotion/query/mapper/PromotionGoodsQueryMapper.java
- src/main/java/com/beauty4u/backend/promotion/query/service/PromotionGoodsQueryService.java
- src/main/resources/mapper/promotion/PromotionGoodsMapper.xml
🌟개요
---
프로모션 상품 목록 조회 백 기능 구현
🌐연결된 Issues
---
Closes #207 
📋작업사항
---
- 프로모션 상품 목록 조회 백 기능 구현
- 프로모션 상품 페이지쪽에서 사용할 기능
- 페이징 처리와 상품으로 검색 기능, 정렬 기능 추가
---
✅체크리스트
---
> feat: 프로모션 상품 목록 조회 백 기능 구현

- src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/inform/query/dto/InformListResDTO.java
- src/main/java/com/beauty4u/backend/teamspace/command/application/controller/TeamBoardCommandController.java
- src/main/java/com/beauty4u/backend/teamspace/command/application/controller/TeamBoardReplyCommandController.java
- src/main/java/com/beauty4u/backend/teamspace/command/application/dto/teamboard/TeamBoardReplyReqDTO.java
- src/main/java/com/beauty4u/backend/teamspace/command/application/dto/teamboard/TeamBoardReqDTO.java
- src/main/java/com/beauty4u/backend/teamspace/command/application/service/TeamBoardReplyService.java
- src/main/java/com/beauty4u/backend/teamspace/command/application/service/TeamBoardService.java
- src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/TeamBoard.java
- src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/TeamBoardReply.java
- src/main/java/com/beauty4u/backend/teamspace/command/domain/repository/TeamBoardReplyRepository.java
- src/main/java/com/beauty4u/backend/teamspace/command/domain/repository/TeamBoardRepository.java
- src/main/java/com/beauty4u/backend/teamspace/command/domain/service/TeamBoardDomainService.java
- src/main/java/com/beauty4u/backend/teamspace/command/domain/service/TeamBoardReplyDomainService.java
- src/main/java/com/beauty4u/backend/teamspace/query/controller/TeamBoardQueryController.java
- src/main/java/com/beauty4u/backend/teamspace/query/dto/teamboard/TeamBoardDetailDTO.java
- src/main/java/com/beauty4u/backend/teamspace/query/dto/teamboard/TeamBoardDetailResDTO.java
- src/main/java/com/beauty4u/backend/teamspace/query/dto/teamboard/TeamBoardFilterDTO.java
- src/main/java/com/beauty4u/backend/teamspace/query/dto/teamboard/TeamBoardListDTO.java
- src/main/java/com/beauty4u/backend/teamspace/query/dto/teamboard/TeamBoardListResDTO.java
- src/main/java/com/beauty4u/backend/teamspace/query/dto/teamboard/TeamBoardReplyListDTO.java
- src/main/java/com/beauty4u/backend/teamspace/query/mapper/TeamBoardQueryMapper.java
- src/main/java/com/beauty4u/backend/teamspace/query/service/TeamBoardQueryService.java
- src/main/resources/mapper/teamSpace/teamboard/TeamBoardMapper.xml
🌟개요
---
- 팀 게시판 관련 crud 구현
🌐연결된 Issues
---
Closes #208 
📋작업사항
---
- 팀 게시판 글 관련 crud 구현
- 팀 게시판 댓글 관련 crud 구현
---
✅체크리스트
---
> feat: 팀 게시판 관련 crud 구현

- src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/promotion/query/controller/PromotionGoodsQueryController.java
- src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionGoodsCommonInfoFilterDTO.java
- src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionGoodsCommonInfoResDTO.java
- src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionGoodsSalesDTO.java
- src/main/java/com/beauty4u/backend/promotion/query/mapper/PromotionGoodsQueryMapper.java
- src/main/java/com/beauty4u/backend/promotion/query/service/PromotionGoodsQueryService.java
- src/main/resources/mapper/promotion/PromotionGoodsMapper.xml
🌟개요
---
특정 상품에 대한 프로모션 정보 리스트 조회 백 기능 구현
🌐연결된 Issues
---
Closes #200 
📋작업사항
---
- 특정 상품에 대한 프로모션 정보를 목록으로 조회하는 기능 구현
- 프로모션에 대한 제품 매출액, 해당 제품의 1년동안의 평균 매출액, 두개의 대한 대비 증감율을 구하는 로직 구현
---
✅체크리스트
---
> feat: 특정 상품에 대한 프로모션 정보 리스트 조회 백 기능 구현

- src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/goods/query/controller/GoodsSalesQueryController.java
- src/main/java/com/beauty4u/backend/goods/query/dto/GoodsSalesFilterDTO.java
- src/main/java/com/beauty4u/backend/goods/query/dto/GoodsSalesResDTO.java
- src/main/java/com/beauty4u/backend/goods/query/mapper/GoodsSalesQueryMapper.java
- src/main/java/com/beauty4u/backend/goods/query/service/GoodsSalesQueryService.java
- src/main/resources/mapper/goods/GoodsSalesMapper.xml
🌟개요
---
제품의 전년 대비 같은 월 비교 백 기능 구현
🌐연결된 Issues
---
Closes #213 
📋작업사항
---
- 제품의 전년 대비 같은 월 비교 백 기능 구현
- 기준 연월에 대한 매출액 조회 로직 구현
- 두 개의 매출액에 대한 비교로 증감율 계산 구현
---
✅체크리스트
---
> feat: 제품의 전년 대비 같은 월 비교 백 기능 구현

- src/main/java/com/beauty4u/backend/file/command/application/controller/FileController.java
- src/main/java/com/beauty4u/backend/file/command/application/dto/FileDTO.java
- src/main/java/com/beauty4u/backend/file/command/application/dto/FileDeleteReqDTO.java
- src/main/java/com/beauty4u/backend/file/command/application/dto/FileSaveReqDTO.java
- src/main/java/com/beauty4u/backend/file/command/application/service/FileService.java
- src/main/java/com/beauty4u/backend/file/command/domain/aggregate/FileInfo.java
- src/main/java/com/beauty4u/backend/file/command/domain/repository/FileRepository.java
- src/main/java/com/beauty4u/backend/file/command/domain/service/FileDomainService.java
- src/main/java/com/beauty4u/backend/inform/command/application/service/InformService.java
- src/main/java/com/beauty4u/backend/inform/query/controller/InformQueryController.java
- src/main/java/com/beauty4u/backend/teamspace/command/application/controller/TeamBoardCommandController.java
- src/main/java/com/beauty4u/backend/teamspace/command/application/controller/TeamBoardReplyCommandController.java
- src/main/java/com/beauty4u/backend/teamspace/command/application/dto/TeamBoardDTO.java
- src/main/java/com/beauty4u/backend/teamspace/command/domain/service/TeamBoardDomainService.java
- src/main/java/com/beauty4u/backend/teamspace/query/controller/TeamBoardQueryController.java
🌟개요
---
- 파일 업로드 리팩토링
🌐연결된 Issues
---
Closes #212 
📋작업사항
---
- 파일 업로드 리팩토링
---
✅체크리스트
---
> refactor: 파일 업로드 리팩토링

- src/main/java/com/beauty4u/backend/teamspace/command/application/controller/TeamSpaceCommandController.java
- src/main/java/com/beauty4u/backend/teamspace/command/application/service/TeamSpaceService.java
- src/main/java/com/beauty4u/backend/teamspace/command/domain/repository/TeamSpaceRepository.java
- src/main/java/com/beauty4u/backend/teamspace/query/controller/TeamSpaceQueryController.java
- src/main/java/com/beauty4u/backend/teamspace/query/mapper/TeamSpaceQueryMapper.java
- src/main/java/com/beauty4u/backend/teamspace/query/service/TeamSpaceQueryService.java
- src/main/resources/mapper/teamSpace/TeamSpaceMapper.xml
🌟개요
🌐연결된 Issues
---
Closes #192 
📋작업사항
--- 초기 실행시 부서 코드에 해당되는 팀스페이스가 생성되도록 구현(중복생성 x)
--- 부서 코드로 본인의 팀스페이스 조회 가능하도록 구현
---
✅체크리스트
> feat: 팀스페이스 생성 및 조회

- Dockerfile
- docker-compose.yml
🌟개요
---
엘라스틱 서치 노리분석기 설정 적용
🌐연결된 Issues
---
Closes #219 
📋작업사항
---
엘라스틱 서치 적용에 노리분석기 설정값을 위한 yml 수정
---
✅체크리스트
---
> chore: 엘라스틱서치 노리분석기 적용, yml 수정

- src/main/resources/mapper/promotion/PromotionMapper.xml
🌟개요
---
프로모션 종류 추가로 인한 프로모션 목록 조회 mapper.xml 수정
🌐연결된 Issues
---
Closes #221
📋작업사항
---
- 프로모션 종류 추가로 인한 프로모션 목록 조회 mapper.xml 수정
---
✅체크리스트
---
> fix: 프로모션 종류 추가로 인한 프로모션 목록 조회 mapper.xml 수정

- src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/goods/query/controller/GoodsQueryController.java
- src/main/java/com/beauty4u/backend/goods/query/dto/TopCategoryResDTO.java
- src/main/java/com/beauty4u/backend/goods/query/mapper/CategoryQueryMapper.java
- src/main/java/com/beauty4u/backend/goods/query/service/GoodsQueryService.java
- src/main/java/com/beauty4u/backend/promotion/command/application/dto/SavePromotionReqDTO.java
- src/main/java/com/beauty4u/backend/promotion/command/application/dto/UpdatePromotionGoodsListReqDTO.java
- src/main/java/com/beauty4u/backend/promotion/command/domain/aggregate/Promotion.java
- src/main/java/com/beauty4u/backend/promotion/command/domain/aggregate/PromotionGoods.java
- src/main/java/com/beauty4u/backend/promotion/command/domain/service/PromotionDomainService.java
- src/main/java/com/beauty4u/backend/promotion/command/domain/service/PromotionGoodsDomainService.java
- src/main/java/com/beauty4u/backend/promotion/query/controller/PromotionGoodsQueryController.java
- src/main/resources/mapper/goods/CategoryMapper.xml
🌟개요
---
프로모션 오류 수정
🌐연결된 Issues
---
Closes #221
📋작업사항
---
- 프로모션 오류 수정
---
✅체크리스트
---
> fix: 프로모션 오류 수정

- src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
- src/main/java/com/beauty4u/backend/goods/query/controller/GoodsQueryController.java
- src/main/java/com/beauty4u/backend/goods/query/dto/GoodsFilterReqDTO.java
- src/main/java/com/beauty4u/backend/goods/query/mapper/GoodsQueryMapper.java
- src/main/java/com/beauty4u/backend/goods/query/service/GoodsQueryService.java
- src/main/resources/mapper/goods/GoodsMapper.xml
🌟개요
---
상품 필터링 조건으로 목록 조회 기능 구현
🌐연결된 Issues
---
Closes #225 
📋작업사항
---
- 상품 필터링 조건으로 목록 조회 기능 구현
---
✅체크리스트
---
> feat: 상품 필터링 조건으로 목록 조회 기능 구현

- src/main/java/com/beauty4u/backend/promotion/command/application/controller/PromotionController.java
- src/main/java/com/beauty4u/backend/promotion/command/application/service/PromotionService.java
- src/main/java/com/beauty4u/backend/promotion/command/domain/service/PromotionDomainService.java
- src/main/resources/mapper/noti/NotiMapper.xml
🌟개요
---
- 프로모션 등록 기능에서 등록된 프로모션 번호를 반환하도록 수정
🌐연결된 Issues
---
Closes #227 
📋작업사항
---
- 프로모션 등록 수정
---
- 알림 조회 오류 수정
✅체크리스트
---
> refactor: 프로모션 등록 수정

- src/main/java/com/beauty4u/backend/analysis/query/controller/AnalysisQueryController.java
- src/main/java/com/beauty4u/backend/analysis/query/dto/response/AnalysisAgeGroupRadioResDTO.java
- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/promotion/query/controller/PromotionStatisticalQueryController.java
- src/main/java/com/beauty4u/backend/promotion/query/dto/FindComToPrevPromoGoodsSalesRankResDTO.java
- src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionByComparisonSalesResDTO.java
- src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionByTypeResDTO.java
- src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionByYearSalesResDTO.java
- src/main/java/com/beauty4u/backend/promotion/query/mapper/PromotionStatisticalMapper.java
- src/main/java/com/beauty4u/backend/promotion/query/service/PromotionStatisticalQueryService.java
- src/main/resources/mapper/analysis/analysisMapper.xml
- src/main/resources/mapper/promotion/PromotionStatisticalMapper.xml
- src/test/java/com/beauty4u/backend/analysis/query/service/AnalysisQueryServiceTest.java
- src/test/java/com/beauty4u/backend/promotion/query/service/PromotionStatisticalQueryServiceTest.java
🌟개요
---
🌐연결된 Issues
---
Closes #218
📋작업사항
---
- 프로모션 타입별 조회 ASC 조회
- 프로모션 종류에 따른 년도별 그래프 조회
- 프로모션 기간 상품 매출 랭킹 비교
---
✅체크리스트
---
> Feat: 프로모션 비교 분석 기능 구현

- src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionGoodsListResDTO.java
- src/main/java/com/beauty4u/backend/promotion/query/dto/PromotionDetailResDTO.java
- src/main/java/com/beauty4u/backend/promotion/query/mapper/PromotionGoodsQueryMapper.java
- src/main/resources/mapper/promotion/PromotionGoodsMapper.xml
- src/main/resources/mapper/promotion/PromotionMapper.xml
🌟개요
---
- 프로모션 상세 조회, 적용 상품 조회 수정
🌐연결된 Issues
---
Closes #227 
📋작업사항
---
- 프로모션 상세 조회, 적용 상품 조회 수정
- 응답 데이터를 추가 했습니다.
---
✅체크리스트
---
> refactor: 프로모션 상세 조회, 적용 상품 조회 수정

- src/main/java/com/beauty4u/backend/goods/query/controller/GoodsQueryController.java
- src/main/java/com/beauty4u/backend/goods/query/service/GoodsQueryService.java
- src/main/resources/mapper/goods/GoodsRateMapper.xml
🌟개요
---
날짜별 매출 증감률 조회를 수정했습니다.
🌐연결된 Issues
---
Closes #237 
📋작업사항
---
- 날짜별 매출 증감률 계산 수정 
---
- 일일 조회가 아직 나오지 않습니다.
- 더미데이터가 많이 필요할 듯 합니다.
- 엘라스틱 서치 빠진 부분 수정했습니다.
✅체크리스트
---
> chore: 날짜별 매출 증감률 조회 수정

- readme.md
🌟개요
---
기술 스택 작성
🌐연결된 Issues
---
Closes #230 
📋작업사항
---
- 리드미에 기술 스택 작성
---
✅체크리스트
---
> docs: 기술 스택 작성

- src/main/java/com/beauty4u/backend/schedule/command/application/controller/ScheduleCommandController.java
- src/main/java/com/beauty4u/backend/schedule/command/application/dto/CreateScheduleReqDTO.java
- src/main/java/com/beauty4u/backend/schedule/command/application/service/ScheduleService.java
- src/main/java/com/beauty4u/backend/schedule/command/domain/aggregate/ScheduleInfo.java
- src/main/java/com/beauty4u/backend/schedule/command/domain/service/ScheduleDomainService.java
🌟개요
---
- 일정 등록 리팩토링
🌐연결된 Issues
---
Closes #239 
📋작업사항
---
- 일정 등록 리팩토링
---
✅체크리스트
---
> refactor: 일정 등록 리팩토링

- src/main/java/com/beauty4u/backend/goods/query/controller/GoodsSalesQueryController.java
- src/main/java/com/beauty4u/backend/goods/query/dto/GoodsFilterReqDTO.java
- src/main/java/com/beauty4u/backend/goods/query/mapper/GoodsQueryMapper.java
- src/main/java/com/beauty4u/backend/goods/query/service/GoodsQueryService.java
- src/main/java/com/beauty4u/backend/goods/query/service/GoodsSalesQueryService.java
- src/main/java/com/beauty4u/backend/promotion/query/controller/PromotionGoodsQueryController.java
- src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionGoodsCommonInfoResDTO.java
- src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionGoodsSalesDTO.java
- src/main/java/com/beauty4u/backend/promotion/query/mapper/PromotionGoodsQueryMapper.java
- src/main/java/com/beauty4u/backend/promotion/query/service/PromotionGoodsQueryService.java
- src/main/resources/mapper/goods/GoodsMapper.xml
- src/main/resources/mapper/promotion/PromotionGoodsMapper.xml
- src/main/resources/mapper/promotion/PromotionMapper.xml
- src/main/resources/mapper/promotion/PromotionStatisticalMapper.xml
🌟개요
---
지금까지의 오류 수정
🌐연결된 Issues
---
Closes #244 
📋작업사항
---
- 지금까지의 프론트와의 오류 수정
---
✅체크리스트
---
> fix: 지금까지의 오류 수정

- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/promotion/query/controller/PromotionStatisticalQueryController.java
- src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionReqDTO.java
- src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionResDTO.java
- src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionTypeResDTO.java
- src/main/java/com/beauty4u/backend/promotion/query/mapper/PromotionStatisticalMapper.java
- src/main/java/com/beauty4u/backend/promotion/query/service/PromotionStatisticalQueryService.java
- src/main/resources/mapper/promotion/PromotionStatisticalMapper.xml
🌟개요
---
🌐연결된 Issues
---
Closes #{이슈넘버}
📋작업사항
---
- 시간 관계상 구현 할 수 없었던 검색 기능 구현하였습니다.
- 필요한 메소드들을 작성하여 백엔드 기능 구현중입니다.
---
- 이슈는 아직 닫지 않겠습니다 계속해서 개발을 해야함.
✅체크리스트
---
> Refactor: 프로모션 통계 분석 검색 기능 구현

- src/main/java/com/beauty4u/backend/elasticsearch/ElasticsearchIndexInitializer.java
- src/main/java/com/beauty4u/backend/goods/query/elasticsearch/document/GoodsDocument.java
- src/main/java/com/beauty4u/backend/goods/query/elasticsearch/repository/GoodsSearchRepository.java
- src/main/resources/elasticsearch/mappings/mappings.json
- src/main/resources/elasticsearch/settings/settings.json
- src/main/resources/mapper/goods/GoodsRateMapper.xml
🌟개요
---
엘라스틱 서치를 활용한 검색 기능 고도화
🌐연결된 Issues
---
Closes #247 
📋작업사항
---
- 엘라스틱 서치를 활용한 연관검색, 오타검색 추가를 위해 settings, mappings 파일 수정
---
✅체크리스트
---
> chore: 엘라스틱 서치 커스튬 적용

- src/main/java/com/beauty4u/backend/goods/query/controller/GoodsQueryController.java
- src/main/java/com/beauty4u/backend/goods/query/dto/GoodsListResDTO.java
- src/main/java/com/beauty4u/backend/goods/query/mapper/GoodsQueryMapper.java
- src/main/java/com/beauty4u/backend/goods/query/service/GoodsQueryService.java
- src/main/resources/mapper/goods/GoodsMapper.xml
🌟개요
---
상품 조회 화면 페이징 추가
🌐연결된 Issues
---
Closes #250 
📋작업사항
---
---
✅체크리스트
---
> chore: 상품 목록 조회 페이징 처리 추가

- src/main/java/com/beauty4u/backend/common/util/CustomUserUtil.java
- src/main/java/com/beauty4u/backend/noti/command/domain/aggregate/NotiType.java
- src/main/java/com/beauty4u/backend/noti/command/domain/service/NotiDomainService.java
- src/main/java/com/beauty4u/backend/noti/query/controller/NotiQueryController.java
- src/main/java/com/beauty4u/backend/schedule/command/application/controller/ScheduleCommandController.java
- src/main/java/com/beauty4u/backend/schedule/command/application/service/ScheduleService.java
- src/main/java/com/beauty4u/backend/user/query/mapper/UserQueryMapper.java
- src/main/java/com/beauty4u/backend/user/query/service/UserQueryService.java
- src/main/resources/mapper/noti/NotiMapper.xml
- src/main/resources/mapper/user/UserMapper.xml
🌟개요
---
- 일정 등록시 SSE 알림 발송되도록 리팩토링
🌐연결된 Issues
---
Closes #253 
📋작업사항
---
- 일정 등록시 SSE 알림 발송되도록 리팩토링
---
✅체크리스트
---
> refactor: 일정 등록시 SSE 알림 발송되도록 리팩토링

- src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
- src/main/java/com/beauty4u/backend/user/query/controller/UserQueryController.java
- src/main/java/com/beauty4u/backend/user/query/dto/UserListDTO.java
- src/main/java/com/beauty4u/backend/user/query/dto/UserListResDTO.java
- src/main/java/com/beauty4u/backend/user/query/mapper/UserQueryMapper.java
- src/main/java/com/beauty4u/backend/user/query/service/UserQueryService.java
- src/main/resources/mapper/user/UserMapper.xml
- src/test/java/com/beauty4u/backend/user/query/service/UserQueryServiceTest.java
🌟개요
---
userList 페이징 처리 로직 리팩토링
🌐연결된 Issues
---
Closes #249
📋작업사항
---
- userList 요청에서 페이징 처리를 위한 로직 수정
- 전체 요소의 개수를 같이 반환
- 로직 변경으로 인한 test 코드도 수정
---
✅체크리스트
---
> refactor: userList 페이징 처리 로직 리팩토링

- src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
- src/main/java/com/beauty4u/backend/common/util/CustomUserUtil.java
- src/main/java/com/beauty4u/backend/inquiry/command/application/controller/InquiryCommandController.java
- src/main/java/com/beauty4u/backend/inquiry/command/application/service/InquiryService.java
- src/main/java/com/beauty4u/backend/inquiry/command/domain/service/InquiryDomainService.java
🌟개요
---
자신의 문의만 수정하도록 변경
🌐연결된 Issues
---
Closes #249 
📋작업사항
---
- 자신의 문의만 수정하도록 변경
---
✅체크리스트
---
> refactor: 자신의 문의만 수정하도록 변경

- src/main/java/com/beauty4u/backend/promotion/query/controller/PromotionStatisticalQueryController.java
- src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionByYearSalesResDTO.java
- src/main/resources/mapper/promotion/PromotionStatisticalMapper.xml
🌟개요
---
🌐연결된 Issues
---
Closes #{이슈넘버}
📋작업사항
---
- 그래프 기능 리팩토링 완료
---
✅체크리스트
---
> refactor: 프로모션 분석 그래프 기능 리팩토링 완료

- src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/inquiry/command/application/controller/InquiryReplyCommandController.java
- src/main/java/com/beauty4u/backend/inquiry/command/application/service/InquiryReplyService.java
- src/main/java/com/beauty4u/backend/inquiry/command/domain/aggregate/InquiryReply.java
- src/main/java/com/beauty4u/backend/inquiry/command/domain/service/InquiryReplyDomainService.java
- src/main/java/com/beauty4u/backend/inquiry/query/controller/InquiryReplyQueryController.java
- src/main/java/com/beauty4u/backend/inquiry/query/dto/InquiryReplyResDTO.java
- src/main/java/com/beauty4u/backend/inquiry/query/mapper/InquiryReplyQueryMapper.java
- src/main/java/com/beauty4u/backend/inquiry/query/service/InquiryReplyQueryService.java
- src/main/resources/mapper/inquiry/InquiryReplyMapper.xml
🌟개요
---
QnA 답변 로직 추가 및 리팩토링
🌐연결된 Issues
---
Closes #259 
Closes #261
📋작업사항
---
- QnA 답변 수정, 삭제 endPoint 변경
- QnA 답변 삭제 시 상태값 바뀌도록 설정
- QnA 답변 조회 기능 추가
---
✅체크리스트
---
> feat: QnA 답변 로직 추가 및 리팩토링

- src/main/java/com/beauty4u/backend/goods_rate/query/dto/GoodsRateQueryDTO.java
- src/main/resources/mapper/goods/GoodsRateMapper.xml
🌟개요
---
상품 분석 화면 이동 위한 코드 추가
🌐연결된 Issues
---
Closes #265 
📋작업사항
---
상품 분석 화면 이동하기 위해 상품코드를 추가하였습니다.
---
✅체크리스트
---
> chore: 상품 분석 조회 위한 상품 코드 추가

- src/main/java/com/beauty4u/backend/promotion/query/mapper/PromotionQueryMapper.java
- src/main/java/com/beauty4u/backend/promotion/query/service/PromotionQueryService.java
- src/main/java/com/beauty4u/backend/security/config/SecurityConfig.java
🌟개요
---
공지사항 등록, 수정, 삭제 권한 설정 추가
🌐연결된 Issues
---
Closes #267 
📋작업사항
---
---
✅체크리스트
---
> refactor: 공지사항 등록, 수정, 삭제 권한 설정

- src/main/resources/mapper/goods/GoodsRateMapper.xml
🌟개요
---
메인화면 상품 매출률 조회 더보기 칸을 클릭해 매출 증감률 전체를 볼 수 있습니다.
🌐연결된 Issues
---
Closes #270 
📋작업사항
---
- 백엔드 쿼리문 개수 제한 삭제
---
✅체크리스트
---
> chore: 상품 분석 조회 위한 상품 코드 개수 삭제

- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/promotion/query/controller/PromotionStatisticalQueryController.java
- src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionByComparisonResDTO.java
- src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionByGoodsSalesResDTO.java
- src/main/java/com/beauty4u/backend/promotion/query/mapper/PromotionStatisticalMapper.java
- src/main/java/com/beauty4u/backend/promotion/query/service/PromotionStatisticalQueryService.java
- src/main/resources/mapper/promotion/PromotionStatisticalMapper.xml
🌟개요
---
🌐연결된 Issues
---
Closes #243
📋작업사항
---
- 백엔드 작업 완료
---
✅체크리스트
---
> refactor: 프로모션 분석 페이지 구현 #243

- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/promotion/command/application/controller/PromotionNotiController.java
- src/main/java/com/beauty4u/backend/promotion/command/application/dto/SavePromotionNotiDTO.java
- src/main/java/com/beauty4u/backend/promotion/command/application/dto/UpdatePromotionNotiDTO.java
- src/main/java/com/beauty4u/backend/promotion/command/application/service/PromotionNotiService.java
- src/main/java/com/beauty4u/backend/promotion/command/domain/aggregate/PromotionNoti.java
- src/main/java/com/beauty4u/backend/promotion/command/domain/repository/PromotionNotiRepository.java
- src/main/java/com/beauty4u/backend/promotion/command/domain/service/PromotionNotiDomainService.java
🌟개요
---
🌐연결된 Issues
---
Closes 
📋작업사항
---
- 프로모션 알림 CRUD 구현
---
✅체크리스트
---
> feat: 프로모션 알림 CRUD #273

- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/file/command/application/controller/FileController.java
- src/main/java/com/beauty4u/backend/file/query/controller/FileQueryController.java
- src/main/java/com/beauty4u/backend/file/query/dto/FileListReqDTO.java
- src/main/java/com/beauty4u/backend/file/query/dto/FileListResDTO.java
- src/main/java/com/beauty4u/backend/file/query/mapper/FileQueryMapper.java
- src/main/java/com/beauty4u/backend/file/query/service/FileQueryService.java
- src/main/resources/mapper/file/FileMapper.xml
- src/main/resources/mapper/teamSpace/teamboard/TeamBoardMapper.xml
🌟개요
---
- 특정 게시글에 업로드 된 파일 목록 조회
🌐연결된 Issues
---
Closes #285 
📋작업사항
---
- 특정 게시글에 업로드 된 파일 목록 조회
---
✅체크리스트
---
> feat: 특정 게시글에 업로드 된 파일 목록 조회

- src/main/java/com/beauty4u/backend/promotion/command/application/controller/PromotionNotiController.java
- src/main/java/com/beauty4u/backend/promotion/command/application/service/PromotionNotiService.java
- src/main/java/com/beauty4u/backend/promotion/command/domain/repository/PromotionNotiRepository.java
- src/main/java/com/beauty4u/backend/promotion/command/domain/service/PromotionNotiDomainService.java
- src/main/java/com/beauty4u/backend/promotion/query/controller/PromotionNotiQueryController.java
- src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionByCustomerGoodsResDTO.java
- src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionByCustomerListResDTO.java
- src/main/java/com/beauty4u/backend/promotion/query/mapper/PromotionNotiQueryMapper.java
- src/main/java/com/beauty4u/backend/promotion/query/service/PromotionNotiQueryService.java
- src/main/resources/mapper/promotion/PromotionNotiQueryMapper.xml
🌟개요
---
🌐연결된 Issues
---
Closes #273
📋작업사항
---
- 프로모션 선택 기능 구현 (검색가능)
- 선택한 프로모션 대상자 목록 조회 기능 구현
- 프로모션 알림 전송 기능 구현 (이메일 미구현)
- 프로모션 Noti 테이블에 해당 알림 저장 기능 구현
---
✅체크리스트
---
> feat: 프로모션 알림 기능 구현

- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/config/gemini/GeminiRestTemplateConfig.java
- src/main/java/com/beauty4u/backend/goods/command/domain/repository/ReviewRepository.java
- src/main/java/com/beauty4u/backend/goods/query/controller/ReviewAiQueryController.java
- src/main/java/com/beauty4u/backend/goods/query/dto/GeminiRequestDTO.java
- src/main/java/com/beauty4u/backend/goods/query/dto/GeminiResponse.java
- src/main/java/com/beauty4u/backend/goods/query/dto/GeminiReviewResDTO.java
- src/main/java/com/beauty4u/backend/goods/query/service/GeminiReviewQueryService.java
🌟개요
---
제미나이 리뷰 요약 기능 추가
🌐연결된 Issues
---
Closes #282 
📋작업사항
---
- 제미나이 리뷰 요약 기능 추가
---
✅체크리스트
---
> feat: 제미나이 리뷰 요약 기능 추가

- src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/config/gemini/GeminiRestTemplateConfig.java
- src/main/java/com/beauty4u/backend/goods/command/domain/repository/ReviewRepository.java
- src/main/java/com/beauty4u/backend/goods/query/controller/ReviewAiQueryController.java
- src/main/java/com/beauty4u/backend/goods/query/dto/GeminiRequestDTO.java
- src/main/java/com/beauty4u/backend/goods/query/dto/GeminiResponse.java
- src/main/java/com/beauty4u/backend/goods/query/dto/GeminiReviewResDTO.java
- src/main/java/com/beauty4u/backend/goods/query/service/GeminiReviewQueryService.java
- src/main/java/com/beauty4u/backend/promotion/command/application/dto/SavePromotionReqDTO.java
- src/main/java/com/beauty4u/backend/promotion/command/application/service/PromotionService.java
- src/main/java/com/beauty4u/backend/promotion/command/domain/aggregate/PromotionType.java
- src/main/java/com/beauty4u/backend/promotion/command/domain/repository/PromotionRepository.java
- src/main/java/com/beauty4u/backend/promotion/command/domain/service/PromotionDomainService.java
🌟개요
---
프로모션 등록, 수정 로직 변경
🌐연결된 Issues
---
Closes #275 
📋작업사항
---
- 프로모션 등록과 수정 시 같은 해에 프로모션 종류에 대한 프로모션은 1개만 등록, 수정할 수 있도록 로직 변경
---
✅체크리스트
---
> refactor: 프로모션 등록, 수정에서의 로직 변경

- build.gradle
- src/main/java/com/beauty4u/backend/BackendApplication.java
- src/main/java/com/beauty4u/backend/analysis/command/application/controller/AprioriController.java
- src/main/java/com/beauty4u/backend/analysis/command/application/dto/AprioriRequest.java
- src/main/java/com/beauty4u/backend/analysis/command/application/dto/AprioriResDTO.java
- src/main/java/com/beauty4u/backend/analysis/command/application/dto/AprioriResponse.java
- src/main/java/com/beauty4u/backend/analysis/command/application/service/AprioriService.java
- src/main/java/com/beauty4u/backend/analysis/command/domain/aggregate/AssociationRecommendation.java
- src/main/java/com/beauty4u/backend/analysis/command/domain/repository/AnalysisRepository.java
- src/main/java/com/beauty4u/backend/analysis/command/domain/repository/AssociationRecommendationRepository.java
- src/main/java/com/beauty4u/backend/analysis/command/domain/service/AssociationRecommendationDomainService.java
- src/main/java/com/beauty4u/backend/analysis/command/infrastructure/flaskApi/AprioriClient.java
- src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/config/feignConfig/FeignConfiguration.java
- src/main/java/com/beauty4u/backend/promotion/command/domain/repository/PromotionRepository.java
- src/main/resources/application.yml
🌟개요
---
flask 연관분석 api 연결
🌐연결된 Issues
---
Closes #288 
📋작업사항
---
- flask 연관분석 api 연결
- api 연결을 위한 dto들 추가
---
✅체크리스트
---
> feat: 연관분석 연결 및 클라이언트 응답 dto 추가

- build.gradle
- src/main/java/com/beauty4u/backend/BackendApplication.java
- src/main/java/com/beauty4u/backend/analysis/command/application/controller/AprioriController.java
- src/main/java/com/beauty4u/backend/analysis/command/application/dto/AprioriRequest.java
- src/main/java/com/beauty4u/backend/analysis/command/application/dto/AprioriResDTO.java
- src/main/java/com/beauty4u/backend/analysis/command/application/dto/AprioriResponse.java
- src/main/java/com/beauty4u/backend/analysis/command/application/service/AprioriService.java
- src/main/java/com/beauty4u/backend/analysis/command/domain/aggregate/AssociationRecommendation.java
- src/main/java/com/beauty4u/backend/analysis/command/domain/repository/AnalysisRepository.java
- src/main/java/com/beauty4u/backend/analysis/command/domain/repository/AssociationRecommendationRepository.java
- src/main/java/com/beauty4u/backend/analysis/command/domain/service/AssociationRecommendationDomainService.java
- src/main/java/com/beauty4u/backend/analysis/command/infrastructure/flaskApi/AprioriClient.java
- src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/config/feignConfig/FeignConfiguration.java
- src/main/java/com/beauty4u/backend/promotion/command/domain/repository/PromotionRepository.java
- src/main/resources/application.yml
🌟개요
---
제미나이 요약 리팩토링
🌐연결된 Issues
---
Closes #290 
📋작업사항
---
- 제미나이 요약 리팩토링
---
✅체크리스트
---
> refactor: 제미나이 요약 리팩토링

- src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/file/command/application/dto/FileDTO.java
- src/main/java/com/beauty4u/backend/file/command/application/service/FileService.java
- src/main/java/com/beauty4u/backend/file/command/domain/service/FileDomainService.java
- src/main/java/com/beauty4u/backend/teamspace/command/application/controller/ChatMemberCommandController.java
- src/main/java/com/beauty4u/backend/teamspace/command/application/controller/ChatRoomCommandController.java
- src/main/java/com/beauty4u/backend/teamspace/command/application/dto/chat/ChatMessageReqDto.java
- src/main/java/com/beauty4u/backend/teamspace/command/application/dto/chatmember/ChatMemberReqDTO.java
- src/main/java/com/beauty4u/backend/teamspace/command/application/dto/chatmember/ChatMemberResDTO.java
- src/main/java/com/beauty4u/backend/teamspace/command/application/service/ChatMemberService.java
- src/main/java/com/beauty4u/backend/teamspace/command/application/service/ChatRoomService.java
- src/main/java/com/beauty4u/backend/teamspace/command/application/service/ChatService.java
- src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/ChatMember.java
- src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/ChatMessage.java
- src/main/java/com/beauty4u/backend/teamspace/command/domain/repository/ChatMemberRepository.java
- src/main/java/com/beauty4u/backend/teamspace/command/domain/repository/ChatMessageRepository.java
- src/main/java/com/beauty4u/backend/teamspace/command/domain/service/ChatMemberDomainService.java
- src/main/java/com/beauty4u/backend/teamspace/command/domain/service/ChatMessageDomainService.java
- src/main/java/com/beauty4u/backend/teamspace/command/domain/service/ChatRoomDomainService.java
- src/main/java/com/beauty4u/backend/teamspace/query/controller/ChatRoomQueryController.java
- src/main/java/com/beauty4u/backend/teamspace/query/dto/chatroom/ChatRoomDTO.java
- src/main/java/com/beauty4u/backend/teamspace/query/mapper/ChatRoomQueryMapper.java
- src/main/java/com/beauty4u/backend/teamspace/query/service/ChatRoomQueryService.java
- src/main/resources/mapper/teamSpace/ChatRoomMapper.xml
🌟개요
---
🌐연결된 Issues
#280 
📋작업사항
--- 본인이 속한 채팅방, 채팅 메세지 조회 추가
--- 메세지 전송시 첨부 파일과 관련하여 엔티티 및 DTO 수정
--- 채팅 친구 초대 기능 추가
> feat: 채팅 CRUD 구현

- src/main/java/com/beauty4u/backend/promotion/command/domain/service/PromotionNotiDomainService.java
🌟개요
---
🌐연결된 Issues
---
Closes #296
📋작업사항
---
- 이메일 수정
---
✅체크리스트
---
> feat: 이메일 전송 수정 #296

- src/main/java/com/beauty4u/backend/analysis/command/application/controller/CollaboFilterController.java
- src/main/java/com/beauty4u/backend/analysis/command/application/dto/CollaboFilterResDTO.java
- src/main/java/com/beauty4u/backend/analysis/command/application/service/CollaboFilterService.java
- src/main/java/com/beauty4u/backend/analysis/command/infrastructure/flaskApi/CollaboFilter.java
- src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
- src/main/java/com/beauty4u/backend/promotion/query/controller/PromotionNotiQueryController.java
- src/main/java/com/beauty4u/backend/promotion/query/mapper/PromotionNotiQueryMapper.java
- src/main/java/com/beauty4u/backend/promotion/query/service/PromotionNotiQueryService.java
- src/main/resources/mapper/promotion/PromotionNotiQueryMapper.xml
🌟개요
---
🌐연결된 Issues
---
Closes #298
📋작업사항
---
- 플라스크 연동 기능을 구현함.
- 고객 맞춤 추천 기능을 Spring Boot와 연동하였음.
- 프론트를 위해 최근 분석 번호를 조회하는 기능을 추가하였음.
---
✅체크리스트
---
> feature: 플라스크 연동 백엔드 기능 구현

- .github/workflows/develop-pr-check.yml
- .github/workflows/main-deploy.yml
- .gitignore
- Dockerfile
- docker-compose.yml
- elastic/Dockerfile
- src/main/resources/application.yml
🌟개요
---
- 깃허브 액션 리팩토링 및 배포 과정 추가
🌐연결된 Issues
---
Closes #300 
📋작업사항
---
- 깃허브 액션 리팩토링 및 배포 과정 추가
---
✅체크리스트
---
> feat, refactor: 깃허브 액션 리팩토링 및 배포 과정 추가

- src/main/java/com/beauty4u/backend/teamspace/command/application/controller/ChatMemberCommandController.java
- src/main/java/com/beauty4u/backend/teamspace/command/application/controller/ChatRoomCommandController.java
- src/main/java/com/beauty4u/backend/teamspace/command/application/dto/chat/ChatMessageReqDto.java
- src/main/java/com/beauty4u/backend/teamspace/command/application/service/ChatMemberService.java
- src/main/java/com/beauty4u/backend/teamspace/command/application/service/ChatRoomService.java
- src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/ChatMessage.java
- src/main/java/com/beauty4u/backend/teamspace/query/controller/ChatRoomQueryController.java
- src/main/resources/mapper/teamSpace/ChatRoomMapper.xml
🌟개요
---
🌐연결된 Issues
---
Closes #280 
📋작업사항
--- 채팅방 추가
--- 채팅방 유저 초대시 선택한 유저들의 유저 코드를 받도록 설정
--- 채팅 메세지 전송시 메세지 생성 시간 타입을 LocalDateTime으로 수정
--- 파일 전송 서비스 로직 수정..
> feat: 채팅방 추가 및 유저 초대 CRUD

- src/main/java/com/beauty4u/backend/file/command/application/controller/FileController.java
- src/main/java/com/beauty4u/backend/file/command/application/service/FileService.java
- src/main/java/com/beauty4u/backend/teamspace/command/application/dto/chat/ChatMessageReqDto.java
- src/main/java/com/beauty4u/backend/teamspace/command/application/service/ChatService.java
- src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/ChatMessage.java
- src/main/java/com/beauty4u/backend/teamspace/command/domain/repository/ChatMessageRepository.java
- src/main/java/com/beauty4u/backend/teamspace/command/domain/service/ChatRoomDomainService.java
- src/main/java/com/beauty4u/backend/teamspace/query/dto/chatMessage/ChatMessageResDto.java
- src/main/java/com/beauty4u/backend/teamspace/query/dto/chatroom/ChatRoomUserInfoDto.java
- src/main/java/com/beauty4u/backend/teamspace/query/service/ChatQueryService.java
- src/main/java/com/beauty4u/backend/teamspace/query/service/ChatRoomQueryService.java
- src/main/resources/mapper/teamSpace/ChatRoomMapper.xml
🌟개요
---
🌐연결된 Issues
---
Closes #316 
📋작업사항
--- 이미지 파일 전송 및 미리보기 구현
--- 이미지 파일 다운로드 가능
> feat: 채팅 파일 전송 기능 구현

- src/main/java/com/beauty4u/backend/promotion/command/application/controller/PromotionNotiController.java
- src/main/java/com/beauty4u/backend/promotion/command/application/service/PromotionNotiService.java
- src/main/java/com/beauty4u/backend/promotion/command/domain/service/PromotionNotiDomainService.java
- src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionByComparisonResDTO.java
- src/main/java/com/beauty4u/backend/promotion/query/mapper/PromotionNotiQueryMapper.java
- src/main/java/com/beauty4u/backend/promotion/query/service/PromotionNotiQueryService.java
- src/main/resources/mapper/promotion/PromotionStatisticalMapper.xml
🌟개요
---
🌐연결된 Issues
---
Closes #310
📋작업사항
---
- 프로모션 분석 SQL 수정
---
✅체크리스트
---
> chore: 쿼리 수정 및 DTO 수정

- .github/workflows/develop-pr-check.yml
- .github/workflows/main-deploy.yml
🌟개요
---
- 깃허브 액션 수정
🌐연결된 Issues
---
Closes #300 
📋작업사항
---
- 깃허브 액션 수정
---
✅체크리스트
---
> refactor: 깃허브 액션 수정

- src/main/resources/application.yml
🌟개요
---
🌐연결된 Issues
---
Closes #304 
📋작업사항
---
- yml 파일 설정 추가 : 외부 통신 TimeOut 1분으로 설정
---
✅체크리스트
---
> chore: yml 파일 설정 추가

- src/main/java/com/beauty4u/backend/promotion/query/controller/PromotionTypeQueryController.java
- src/main/java/com/beauty4u/backend/promotion/query/dto/PromotionTypeList.java
- src/main/java/com/beauty4u/backend/promotion/query/mapper/PromotionTypeQueryMapper.java
- src/main/java/com/beauty4u/backend/promotion/query/service/PromotionTypeQueryService.java
- src/main/resources/mapper/promotion/PromotionTypeMapper.xml
🌟개요
---
프로모션 목록 조회 페이징 처리 구현
🌐연결된 Issues
---
Closes #326 
📋작업사항
---
- 프로모션 목록 조회 페이징 처리 구현
---
✅체크리스트
---
> refactor: 프로모션 목록 조회 페이징 처리 구현

- src/main/java/com/beauty4u/backend/promotion/command/domain/service/PromotionNotiDomainService.java
🌟개요
---
🌐연결된 Issues
---
Closes #328
📋작업사항
---
- 이메일 전송 시 사용하지 않는 고객코드 등록되는 현상 수정
---
✅체크리스트
---
> fix: 이메일 오류 수정 #328

- src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionReqDTO.java
- src/main/resources/mapper/promotion/PromotionStatisticalMapper.xml
🌟개요
---
🌐연결된 Issues
---
Closes #330 
📋작업사항
---
- mapper DTO 수정
---
✅체크리스트
---
> chore: DTO mapper 수정 #330

- src/main/resources/mapper/promotion/PromotionNotiQueryMapper.xml
🌟개요
---
🌐연결된 Issues
---
Closes #332 
📋작업사항
---
- mapper 수정
---
✅체크리스트
---
> chore: mapper 수정 #332

- src/main/java/com/beauty4u/backend/promotion/query/controller/PromotionNotiQueryController.java
- src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionListResDTO.java
- src/main/java/com/beauty4u/backend/promotion/query/mapper/PromotionNotiQueryMapper.java
- src/main/java/com/beauty4u/backend/promotion/query/service/PromotionNotiQueryService.java
- src/main/resources/mapper/promotion/PromotionNotiQueryMapper.xml
🌟개요
---
🌐연결된 Issues
---
Closes #334 
📋작업사항
---
- 프로모션 알림 발송 프로모션 검색 페이징 처리 
---
✅체크리스트
---
> refactor: 페이징 처리 적용 #334
